### PR TITLE
Update/Addition Canvas Customizations Per Guild

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Finished: 11/30/2020 11:56 pm CST

Mission Statement: Basic creature comforts like volume, and welcome settings saved so the bot remembers your settings after restart, and Compatible with hosts like Heroku. (no permanent sqlite DB) Needs to be Re-Saved your settings After the DB wipe(Heroku Only) 

`!welcome yes` will also show your current settings used
image
`!join` so you can trigger it to see your changes
image

Much Love
-Bacon

### CODE REVIEW

**Comment by XtraHottt** [comment]
Hello there!

I would like to know whether is this is compatible with heroku? Will the settings stays the same when restarting it on heroku or it will just resets the entire thing.

**Comment by Bacon-Fixation** [comment]
Heroku doesn't currently keep the json.sqlite file permanently you might have to reset your settings after Heroku does its restart every24 hours  but settings are changeable on any system but Heroku is known to not keep a sqlite3 DB for More than 24 hours

**Comment by galnir** [comment]
Are those features production-ready?

**Comment by Bacon-Fixation** [comment]
Yep yep :D

**Comment by Bacon-Fixation** [comment]
Fixed and Ready
I apologize for that

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
just had a double space in the example section i just had to change

**Comment by Bacon-Fixation** [comment]
Fixed and Ready
I apologize for that

Much Love
-Bacon

**Comment by galnir** [comment]
I think you forgot to remove the 'WecomeMessageTestCommand' from the PR?

**Comment by Bacon-Fixation** [comment]
> I think you forgot to remove the 'WecomeMessageTestCommand' from the PR?

It is the Join command so you can see your welcome message changes

**Review by galnir — APPROVED** [review]

**Pull request merged**
