### PR TITLE
added Pi compatibility

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Wanted to make it easy to install on a  Raspberry Pi without needing to find all the Path errors
this was the easiest solution that worked on all my test beds 

Tested on
Windows 10
Ubuntu
Raspberry OS 10 (debian 10)

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
I swear it's like you read my mind, I have been trying to get a Raspberry Pi to keep my bot online and didn't know if it would work, so thanks lol.

**Comment by Bacon-Fixation** [comment]
I would recommend a pi 3B+ it can handle everything really nicely,
The Zero and Zero W are slow to respond but will still work just slowly most noticeable on `!play` command 
Also if you install Raspberry OS with desktop (recommended install from the Raspberry pi imager app) you will already have
FFmpeg
python2.7
already installed 
just need to install Node 12 or higher and run `npm i ` in the bot folder

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Ok, thanks, and I would assume that a pi 4B would work perfectly fine since that's the one I planned on getting anyway

**Comment by Bacon-Fixation** [comment]
Np I did run into a quirk where when I did a `sudo apt-get install nodejs`  it would only install to 10.x so I wrote down a workaround in the tutorial 

Best of luck

**Review by galnir — APPROVED** [review]

**Pull request merged**
