### PR TITLE
Twitch Feature Ready

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
I apologize for the other closed PR's long night <3

Dev Notes/History https://github.com/galnir/Master-Bot/pull/698

Should be Ready for prime time

`npx prisma migrate dev` is required to add the new tables to your DB

You can add multiple streamers and even to separate text channels 

### Preview 
Twitch Status Command - Online
image
Twitch Status Command - Offline
image
Show Twitch Alerts
image
Twitch Alerts
image

Tested on
Windows 10 (Local)
Raspberry OS 64Bit (arm64/Local)
Debian 10 (Arm64/Local)
Heroku (Web)

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
16 hours in and the Heroku test rig stopped from invalid Access token. Corrected so it will refresh the Token rather than Crash Out

Much Love
-Bacon

**Comment by galnir** [comment]
Can you explain briefly how the feature works so its easier for me to go through it? Also instead of declaring a new model 'GuildTwitch', why not just add the notifyList field to the 'Guild' model?

**Review by galnir — COMMENTED** [review]
Can you explain briefly how the feature works so its easier for me to go through it? Also instead of declaring a new model 'GuildTwitch', why not just add the notifyList field to the 'Guild' model?

**Comment by Bacon-Fixation** [comment]
it calls the Twitch API every 60 seconds to check who is online, if a streamer has started a stream it will send a notification to the text channel that was specified, if the game or title changes then update the previously sent message with the new info, then if the user goes offline, edit that embed to indicate the stream is over.

supports more than just one Twitch Streamer per guild
all of the streamers across all guilds are queried in 100 user chunks  to keep the Number of API calls Low

at the time i was having issues with creating/updating an entry to the Guild model when the values of Volume or notifyList were being set for the first time, or when a user wants to remove the last streamer from the notifyList, i would get a `prisma String[] are not nullable` error,  kinda leaving me having to delete the GuildTwitch entry when a Guild didn't have/want any Streamers to get notifications from

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I realized where my previous issue stemmed from after making the comment....... sigh 

moved notifyList into the Guild Model

Much Love
-Bacon

**Review by galnir — APPROVED** [review]
💯

**Pull request merged**
