### PR TITLE
Reaction Controls

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Addressing #371
was #419 but that had ~40 commits (didn't want to flood the commit history)
Used pagination embeds to make reaction controls for `!play` and `!nowplaying` commands 

### Features
- Adds Links to `!display-playlist` and `!queue` commands
- `!nowplaying` command allows you to bring back the controls in case it's a busy text channel
- Controls react to guild members in the same voice channel as the music to prevent trolling 
- Controls will time out ~30 sec after the song ends (live streams have a 5-min time out and no playback bar)
- Play back bar only updates when a song is added or the buttons are pressed
- Allow you to repeat 1 song in a queue if you wanted to(pressing repeat queue or next will remove the 1  song repeat)
- Volume is saved to the Db at the end of a song or next button is pressed
- Stop Button will make the bot leave the channel and clear the queue 

### Optional settings
1. Delete the old messages when buttons timeout uncomment line 553 `//.setDeleteOnTimeout(true)`
2. Set a maximum timer length for button timeout uncomment line 737 `//if (timer > 300000) timer = 300000; // 5min timer limit`

- Reaction Controls
image

- Embed when songs are added to queue
image

- Links in the Embed `!queue` command
image

- Tested On
Windows 10 (local)
Debian (local)
CentOs7 (Local Docker)
Raspberry OS 10 (arm7 and arm64 Local)
repl.it (Web)
Glitch.com (Web)
Heroku (Web)

Much Love
-Bacon

### CODE REVIEW

**Comment by Princevikas** [comment]
is this aalready merged?

**Comment by Bacon-Fixation** [comment]
Not yet :D, Yesterday there was an update to the playlist links section of the play command, so I merged the fix to this PR to keep it current to the repo

**Comment by Princevikas** [comment]
> Not yet :D, Yesterday there was a bugfix to the playlist links section of the play command, so I merged the fix to this PR to keep it current to the repo
> 
> its ready, just needs to be reviewed by Galnir for Issues

😍😍 can't wait

**Comment by Jriskamm** [comment]
> Not yet :D, Yesterday there was a bugfix to the playlist links section of the play command, so I merged the fix to this PR to keep it current to the repo
> 
> its ready, just needs to be reviewed by Galnir for Issues

when will it be released?

**Comment by galnir** [comment]
@Jriskamm probably this weekend

**Comment by Bacon-Fixation** [comment]
I believe that Galnir may be working on something related to the Play command, or could just be busy.

just hold on a little while longer :D



Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
LOL

**Comment by Natemo6348** [comment]
> LOL that message appeared an i jumped in my chair, accidentally hit close PR....... i need to chill on the coffee

yeah maybe lol

**Comment by Jriskamm** [comment]
> @Jriskamm probably this weekend

yay thank youu

**Comment by Princevikas** [comment]
😀

**Comment by galnir** [comment]
@Bacon-Fixation What is the purpose of the setTimeouts in lines 635, 642?

**Comment by Bacon-Fixation** [comment]
to keep the Buttons from staying to long or leaving to early, it will subtract the stream time from the Song length (in MS) to keep the Reactions for the necessary amount time regardless if the buttons were pressed or not


```
    function buttonTimer(message) {
      let timer;
      const totalDurationObj = message.guild.musicData.nowPlaying.rawDuration;
      let totalDurationInMS = 0;
      Object.keys(totalDurationObj).forEach(function(key) {
        if (key == 'hours') {
          totalDurationInMS =
            totalDurationInMS + totalDurationObj[key] * 3600000;
        } else if (key == 'minutes') {
          totalDurationInMS = totalDurationInMS + totalDurationObj[key] * 60000;
        } else if (key == 'seconds') {
          totalDurationInMS = totalDurationInMS + totalDurationObj[key] * 1000;
        }
      });

      timer =
        totalDurationInMS - message.guild.musicData.songDispatcher.streamTime + 30000;
```

**Comment by galnir** [comment]
> to keep the Buttons from staying to long or leaving to early, it will subtract the stream time from the Song length (in MS) to keep the Reactions for the necessary amount time regardless if the buttons were pressed or not
> 
> ```
>     function buttonTimer(message) {
>       let timer;
>       const totalDurationObj = message.guild.musicData.nowPlaying.rawDuration;
>       let totalDurationInMS = 0;
>       Object.keys(totalDurationObj).forEach(function(key) {
>         if (key == 'hours') {
>           totalDurationInMS =
>             totalDurationInMS + totalDurationObj[key] * 3600000;
>         } else if (key == 'minutes') {
>           totalDurationInMS = totalDurationInMS + totalDurationObj[key] * 60000;
>         } else if (key == 'seconds') {
>           totalDurationInMS = totalDurationInMS + totalDurationObj[key] * 1000;
>         }
>       });
> 
>       timer =
>         totalDurationInMS - message.guild.musicData.songDispatcher.streamTime + 30000;
> ```
> 
> they are only for the Buttons
> 
> Play/Pause has a 10 min timer if it Paused the song then will go back to the proper time when its resumed

Did you try spamming buttons to see if it can make the bot crash?

**Comment by Bacon-Fixation** [comment]
yes i have, i didn't have any issues

**Comment by galnir** [comment]
> yes i have, i didn't have any issues

I have a 2 suggestions:

1. Increase/decrease volume buttons should increase/decrease the volume by 10% for each click 
2. Shouldn't the old embed's buttons be removed once a new one is generated? For example when skipping a song

Also, can someone who isn't in the voice channel use the buttons? 
I'll try to fix the progress bar before merging this PR

**Comment by Bacon-Fixation** [comment]
```
    const channelInfo = message.member.voice.channel.members;
    const rawMembers = Object.fromEntries(channelInfo);
    const memberArray = [Object.keys(rawMembers)];
``` 
keeps the Buttons for use to only people in the voice channel

**Comment by Bacon-Fixation** [comment]
"1. Increase/decrease volume buttons should increase/decrease the volume by 10% for each click"
that sounds good, i had it set to only 1 because  i was thinking it would be more used for minor tweaks to the volume

"2. Shouldn't the old embed's buttons be removed once a new one is generated? For example when skipping a song"
yeah i agree... when i tried that i had a few issues i ran into

if the embed is still adding the reactions when its told to timeout the buttons i would get an `API Error: Unknown Message`

**Comment by Bacon-Fixation** [comment]
i Apologize for the Delay

**Comment by galnir** [comment]
Btw what's the purpose of the progress bar on the embed that is generated right after the bot starts playing a song?

**Comment by Bacon-Fixation** [comment]
it was there so it wasn't such an abrupt change to the embed size when it was updated after a button press

**Review by galnir — APPROVED** [review]
Great job on this, am really grateful for your contributions to this repository 💯 
I'll address the progress bar(not staying in one line) hopefully in the near future

**Pull request merged**
