### PR TITLE
Create bot-status.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Adds a `!bot-status` inspired by [MM-Bot-jays](https://github.com/discordbots-by-max-morris/MM-Bot-Jays/blob/495269a54636bb714cb9b0cc28f3a7dcae74f026/commands/admin/BotStatus.js) Discord.js 11 code 
also thought it may help with Issue debugging if people posted a screen cap of the Dependency list(Kinda like a user-friendly way to list what's installed if or when an Error occurred)

- Raspberry OS 10(a Debian 10 variant on an Arm7 arch)
image

- Windows 10
image

Dependency list comes from the `package.json` so it will be updated when the bot is updated

Both probe-image-size and openweather-apis are part of a near future feature(so just pretend you never saw them <3 they are not part of this PR)

Much Love
-Bacon

### CODE REVIEW

**Comment by galnir** [comment]
The 'uptime' command should be removed then

**Comment by Bacon-Fixation** [comment]
Removed `uptime.js` and also removed the useless comment that was let in `bot-status.js`

Much Love
-Bacon

**Comment by galnir** [comment]
For some reason it says 'with a total of 4 users' for me too, I'll look into it

**Review by galnir — APPROVED** [review]
gj on this one

**Comment by Bacon-Fixation** [comment]
Oh right on, 
was it counting its self and other bots too ? (i can get 4 if i count me and the other bots in that server for me)

**Comment by galnir** [comment]
It was counting only cached users

**Pull request merged**
