### PR TITLE
Added LeaveTimeOut and MaxResponseTime options

### PR DESCRIPTION
**Pull request by meiaihara06**
<p>
    - Edit LeaveTimeOut in options.json to change how much time (in SECONDS) bot should wait before leaving channel due to inactivity. Use 0 for unlimited (bot will not leave channel after music ends) <br><br>
    - Edit MaxResponseTime in options.json to change how much time (in SECONDS) bot should wait for user response in a command <br><br>
    for example if its set to 10 , users just have 10 seconds to response or react after using <code>?play</code>, otherwise command will be cancelled. may help in big public servers<br>
</p>

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
i apologize for Delays, i needed to test the PR <3

the MaxResponseTime should have a number > 0, shouldn't leave a listener Open indefinitely(it can slow down then eventually crash overtime. If someone just keeps searching youtube without canceling/picking an option)
or respond to a random chat message, and accidentally making multiple selections. 
i believe 2.30 minute max should be more than enough time to make a selection

the LeaveTimeout being 0 was fine, i didn't get any crashes or hangups
(if the discord servers AFK timer is triggered bot moves to the AFK channel will not join your voice channel automatically and requires !join to bring the music to you)

Great Job!!!!!!

Much Love
-Bacon

**Comment by meiaihara06** [comment]
Yes i believe there should be limitations for MaxResponseTime , sorry!, my mistake!! and thanks for pointing out :D
Thank you! and I hope I have been helpfull!

**Comment by Bacon-Fixation** [comment]
> Yes i believe there should be limitations for MaxResponseTime , sorry!, my mistake!! and thanks for pointing out :D
> Thank you! and I hope I have been helpfull!

i didn't know either until i tried to break it on purpose :D

and very helpful <3 Thank You, its contributors like you that help make this bot what it is today, and I'm grateful that you took time to do this

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Thank you again <3 you are quick :D

im just retesting with your 0ff5790 version with multiple option settings in the options.json
curious about deleteOldPlayMessage and the inactivity timer set to 0

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
i added a Maximum limit to the LeaveTimeOut of 600 seconds (10 minutes),i think it should disconnect when inactive 
added a 5-second minimum for MaxResponseTime,i think it should have enough time to see the message appear
limits can be removed/changed if someone needs more time on line 41 - 45 in play.js 

i moved the Readme from your other PR to this one for an all-in-one package 

Thank you again for your time an effort with this

Much Love
-Bacon

**Comment by meiaihara06** [comment]
Hey !
Thank you for response 
but sorry I don't think LeaveTimeOut should have maximum , if we set a maximum on this we are closing the way to some features (for example 24/7 , which if I have time I will definitely try to do)
it's up to bot owner to decide it should be Unlimited or not
and wow
i was just commenting and you ,merged the pull   XD
image
anyway thanks :D 
i hope i helped !

**Comment by Bacon-Fixation** [comment]
im not sure on what you mean by 24/7

but the LeaveTimeOut only effects when no songs are playing and nothing is currently in the queue and the bot is still in the voice channel not broadcasting (when it's not doing anything)

and of course would love to see what you mean by 24/7, i am curious

Much Love
-Bacon

**Comment by meiaihara06** [comment]
oh !  sorry!

> LeaveTimeOut takes effect when no songs are playing

I forgot that , again! my mistake 

I really don't know how 24/7 works on the back , because bots that have this feature are closed source 
but it plays music all day and night from a feed. and anytime someone joins music channel there is a music playing 
(my basic idea: users set a feed (livestream / playlist) in options.json and there is a `-24/7` command that plays this playlist or livestream without leaving channel , and if someone uses -24/7 again it stops and bot can be user normally)

maybe it's unnecessary , I love to hear what you think about it

**Comment by Bacon-Fixation** [comment]
That sounds interesting, I will have to check that out my self 

Thank you again <3

Much Love
-Bacon

**Pull request merged**
