### PR TITLE
Google-Translate

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
A free alternative to Yandex 
 
does not require an API key/token
only `npm install @vitalets/google-translate-api`
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
could you maybe add an alias called `translate`?

**Comment by Bacon-Fixation** [comment]
it's separate to let the older users still have what they paid for from Yandex

**Comment by Bacon-Fixation** [comment]
added `aliases: ['gt', 'g-translate', 'gtranslate']`

**Comment by Natemo6348** [comment]
ah ok, I understand, I wasn't even thinking about that

**Comment by galnir** [comment]
I doubt anyone is paying for a Yandex API key in order to use the 'translate' command. 
But what you can do is check if the user has a Yandex api key in their config.json, if yes go ahead and use their API. If not, use the npm package(will be installed anyway)

**Comment by Bacon-Fixation** [comment]
You're probably right, so I just converted it to Google Translate
 
Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Thanks for addressing #397 🥇

**Pull request merged**
