### PR TITLE
Update lyrics.js No more Limit on Lyrics Length 

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Using the Pagination Embeds eliminates the previous restriction of 4096 characters
self deletes after 1 minute 

- Noticed This limit when testing Issue #310
Capture3

- Great song showing it again 
CaptureCroped

- Pages for a cleaner look
Capture2
 
- Tested on
Windows 10
Ubuntu
Raspberry OS 10

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
I'm actually glad you did this, I was getting tired of not being able to look up lyrics for some songs using the bot

**Comment by mkgaming54** [comment]
Thanks @Bacon-Fixation :D

**Comment by Bacon-Fixation** [comment]
Should be Complete Package now

**Review by galnir — APPROVED** [review]
Awesome, thanks for integrating the pagination-embed library in the command 👍

**Pull request merged**
