### PR TITLE
New Gif Commands

### PR DESCRIPTION
**Pull request by PhantomNimbi**
# Details

Basically this is a series of NSFW image commands. I've added an `addgif` command for bot owner(s) and/or developer(s) to use for adding images to the `txt` files from within discord and updated the paths for the `txt` files accordingly.

The `addgif` command is a `dev` group command and is locked to specific role ids to ensure only authorized users can add images to the `txt` files.

### CODE REVIEW

**Comment by PhantomNimbi** [comment]
# NSFW Commands

 * Create hentai.js
 * Create furry.js
 * Create trap.js
 * Create futa.js
 * Create boobs.js
 * Create blowjob.js


# Resources

 * Create Blowjob.txt
 * Create Boobs.txt
 * Create Furry.txt
 * Create Hentai.txt
 * Create Trap.txt
 * Create Jojo.txt
 * Create Gintama.txt
 
 

# Dev Commands
 
 * Create addgif.js

 
 # Updated Commands
 
 * Update gintama.js
 * Update jojo.js

**Comment by PhantomNimbi** [comment]
# Update

 * Updated image links

**Comment by PhantomNimbi** [comment]
# Ready for Review
 * New SFW Gif Commands Created
 * NSFW Gif Commands Created
 * `addgif` Command created
 * `txt` File Paths Updated to work with the new `addgif` command,

**Review by galnir — CHANGES_REQUESTED** [review]
I would prefer to keep the bot as SFW as possible so it would be great if you could remove the NSFW commands. Besides that I can say great job :)

**Comment by PhantomNimbi** [comment]
Sorry for the late reply. I completely forgot about this PR, lol. I got the requested changes made.

**Comment by galnir** [comment]
discord.js v13 was just released so I'm holding on with this PR until we complete the migration to v13

**Pull request closed without merging**
