### PR TITLE
Further improve Dockerfile

### PR DESCRIPTION
**Pull request by rafaeldamasceno**
Also based on #521

- Added .dockerignore with files not necessary to be copied
- Separated dependency and source copy steps to not have to fetch the dependencies at every code change
- Changed image to Node.js alpine
- Removed pm2

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
@rafaeldamasceno can you add `node_modules` to the .dockerignore

to avoid an error cuased by overwritting the dockerimage's "node_modules" folder with the source's folder
other than that it works great!

Much Love
-Bacon

**Comment by rafaeldamasceno** [comment]
Thanks for noticing, added to the `.dockerignore`.

**Comment by rafaeldamasceno** [comment]
> noticed you switched it from python2 -> python3
> im not sure if something has changed with the Dependencies that now lets it compile with python3 instead of 2.7

Yeah, I checked node-gyp and node-canvas's dependencies and as far as I could tell, node-gyp actually dropped python2 support a little while ago, so I used python3 to make sure everything works fine. I've been running the bot with the images built on this Dockerfile and everything seems to be working just fine.

**Comment by Bacon-Fixation** [comment]
im testing python3 installs on Heroku, Glitch, Repl.it, Raspi OS, Debian, Ubuntu, and Windows (the majority of the hosting methods)
if it passes i can update the Readme and Issues templates in new PR and i will ask Galnir to also review it.
i can't remember if canvas and quick.db were the only issues in the past with python3 and maybe Galnir knows something im forgetting 

the Dockerfile works flawlessly, Thank You for your hard work
reduced the file size ~1.6gigs -> ~611meg 
didn't realize you could use Node directly

Much Love
-Bacon

**Pull request merged**
