### PR TITLE
adds a Game Search Command

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
requires an API Key from https://rawg.io/apidocs 
and `"rawgAPI": "API Key"` added to config.json

if `rawgAPI` is not present inside config.json then the game-search command is disabled automatically

Example `!game-search super metroid`
image

image

- Limits
Free accounts have a 20k calls per month

- Notes
I held onto this for about a month while rawg.io was changing the API to require a key to use
they patched the work-around I was using previously :D
it didn't require an API Key when I started making this command

Much Love
-Bacon

### CODE REVIEW

**Review by galnir — CHANGES_REQUESTED** [review]
Great feature seemed to run smoothly.
However, there is no error handling wrapping the promises on lines 34-47. Is that intentional?
You can go with different ways here:
1. Chain a .catch call on the end of fetch and then have an 'if' statement check if the value stored in the variable is undefined or null (or is actually an object returned by the API that has a property indicating failure)
2. Nest the calls inside try catch, but then you'll have to deal with variables being used outside their blocks 
3. Write a function similar to searchSong(lyrics.js) that returns a promise 

The reason error handling is required is that an unexpected API error could crash the bot

**Comment by Bacon-Fixation** [comment]
Yeah, I goofed 

thank you for the heads-up, I went with option 3

Much Love
-Bacon

**Review by galnir — COMMENTED** [review]
Great choice, why did you wrap lines 41-168 with a try-catch tho? From what I see there is no API call that needs to be dealt with incase of an error

**Comment by Bacon-Fixation** [comment]
whoops that is a left over from me figuring it out <3

**Review by galnir — APPROVED** [review]
Thank you for this feature Bacon :)

**Pull request merged**
