### PR TITLE
Update ban.js

### PR DESCRIPTION
**Pull request by Natemo6348**
this is what I had to change on my bot in order to successfully ban. days if you don't know is how many days of messages from userToBan will be deleted (up to 7 I believe). I wanna make it where you can choose the number of days, but I'm not sure exactly how to without possibly breaking it.

### CODE REVIEW

**Comment by Natemo6348** [comment]
if someone could help with adding the arguments for the number of days that would be amazing lol

**Comment by Bacon-Fixation** [comment]
Is this like an auto ban after 7 day,
deleting the last 7 days of messages from the banned user,
not working because Reasons errored,
I don't quite understand your needs.
I would gladly help yeah if I can just want to make sure I'm on the same page

Much Love
-Bacon

**Comment by Natemo6348** [comment]
What I want is to be able to choose how many days worth of messages to delete from the user when they are banned

**Comment by Bacon-Fixation** [comment]
@Natemo6348 I think I have what you wanted in the #285 PR let me know if that is what you wanted

tested on
win 10 
ubuntu
raspberry os 10

Much Love
-Bacon

**Comment by galnir** [comment]
I'll merge @Bacon-Fixation 's pull req

**Pull request closed without merging**
