### PR TITLE
Create invite.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
A basic invite command if `"invite": true` was added to config.json 
if `"invite"` is false  or if `"invite"` is not in config.json command will not be available on command list (no console message)

image

Much Love
-Bacon

### CODE REVIEW

**Comment by galnir** [comment]
I'm not sure this is a good idea for a self-host bot, because if a user runs a bot on his pc he wouldn't want members inviting his bot to other servers(maybe for malicious intents). This is a great command for public bots tho

**Review by galnir — CHANGES_REQUESTED** [review]
Just add a the command description in the readme and its good to go

**Comment by Bacon-Fixation** [comment]
I have a question @galnir, I set up twitch commands in the same way that they can be toggled on or off based on their presences in the config, should they be listed as optional? 

Reasoning for the inquiry

If they are not in config.json then they shouldn't be load to the command registry on bot startup(sounds good in my head anyway :D)

Could also make it easier for new people to enable or disable commands that require a Keys or Tokens like translate (I feel Like fewer people will use it just because it has a cost, leaving a new user to remove commands or leave a broken command on the list adding to possible error messages)

Like if you want these you can add them to the config.json to enable them by adding them with the credentials to the config and have them show on the command list(possibly reduce the number of Error messages a user might encounter after setup)

it's just a thought <3

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Sorry for the late commit didn't realize I added that to the commit, I wanted to ask first

Much Love
-Bacon

**Comment by galnir** [comment]
> I have a question @galnir, I set up twitch commands in the same way that they can be toggled on or off based on their presences in the config, should they be listed as optional in the README.md?
> 
> Reasoning for the inquiry
> 
> If they are not in config.json then they shouldn't be load to the command registry on bot startup(sounds good in my head anyway :D)
> 
> Could also make it easier for new people to enable or disable commands that require a Keys or Tokens like translate (I feel Like fewer people will use it just because it has a cost, leaving a new user to remove commands or leave a broken command on the list adding to possible error messages)
> 
> Like if you want these you can add them to the config.json to enable them by adding them with the credentials to the config and have them show on the command list(possibly reduce the number of Error messages a user might encounter after setup)
> 
> it's just a thought <3
> 
> Much Love
> -Bacon

Imo yeah it should be listed as optional, and also appear in the config.json example as
```invite: false```

**Comment by Bacon-Fixation** [comment]
Up to Date with Current Commit should be ready now sorry for delays 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Adds a Note: about the public bot setting in the dev portal in the README.md

Moved the `if (!invite) return;` to line 6, so it's not in the list during `!help`

Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Thanks for the work you've put in this feature 🥇

**Pull request merged**
