### PR TITLE
8ball command bugfix

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
heyo i kept getting "An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this." so i fixed it

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
i noticed the README.md was missing the !Dog command in the command list so I also added it to the PR.

**Review by galnir — APPROVED** [review]
Thanks for noticing this and taking the time to fix it ;)

**Comment by Natemo6348** [comment]
i am getting that error still and i didn't change anything, any ideas?

**Comment by Natemo6348** [comment]
nvm i figured it out

**Pull request merged**
