### PR TITLE
Added Custom Welcome Image when new members join the server

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Added a basic copyright free template to add flare to your welcome messages for new members
when you have a new member join your Discord server a welcome image will appear with
welcome to "discord Server name"
avatar of the new member and name
truly a custom welcome banner to make the new member feel welcomed into the server

I left comments next to the options to change colors/shadows/dimensions/etc...
For copyright reasons I only supplied a simple gray and a black wallpaper but you can use any image you wish like I did on the last example(would recommend a JPEG for the tiny size)
  
- **Please Note only the Grey and Black are provided** 
(only a single welcome message will appear this was for Demonstration purposes) 
newmembers
*the last one is to show what you can do with it when you add a `wallpaper.jpg` into the `resources/welcome/` Folder

also, some extra info in console at start up with
your bots tag ( Example: Master-Bot#0000 is Ready!)
and the servers it has been invited to
console flare

The only extra library needed is canvas 
just run  `npm i canvas`

added default discord emoji's to the Group Names when doing a `!help` to match the rest of the visuals consistency 

I really love this bot and want to see it grew, I appreciate everyone in the community and wanted to say thank you!  

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
Finalized and Test
if you add this make sure you run `npm i cavas` to install the node lib needed to manipulate the image
for the Welcome Image

Much Love
-Bacon

**Comment by galnir** [comment]
Wait why did you remove canvas from the dependency list?

**Comment by Bacon-Fixation** [comment]
Sorry about that, Wasn't sure if that was the right way to share the Library dependencies still new to npm and Nodejs
i put them back

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Opted for a direct message since discord now allows you to delete/modify the default general channel

**Comment by Bacon-Fixation** [comment]
I'm done with this one.

I apologize for the constant changes (tinkerers curse)
but this is done done done done I swear

Much Love
-Bacon

**Comment by galnir** [comment]
Lots of users have restricted their DM's to friends only. It could cause errors when trying to send the embed to the user via DM

**Pull request merged**
