### PR TITLE
Update ban.js a Response to #283

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
a response to #283
Adds a question of how many days worth of messages to remove when you ban a user

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
This is exactly what I meant, thanks @Bacon-Fixation

**Comment by Bacon-Fixation** [comment]
Yeah max is 7, it should only accept an integer between 0 and 7 when prompted

**Comment by Natemo6348** [comment]
When I tried with 7 it said I provided an invalid days

**Comment by Bacon-Fixation** [comment]
image

**Comment by Bacon-Fixation** [comment]
@Natemo6348 
try now my friend

**Review by galnir — APPROVED** [review]

**Pull request merged**
