### PR TITLE
Music Controls Update - Slash Commands Control Embed

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
- [x] Done https://github.com/galnir/Master-Bot/pull/705#pullrequestreview-969438525 

LOL i needed to take a break from the Twitch Feature Testing :D, so yeahhhhh

/play, /leave, /skip, /skipto, /seek, /pause /resume /volume and /now-playing will delete/alter the old Music Player Embed

Note: the Player Embed will always stay in the text channel that the Player was initiated in, even if you run a music command in a different text channel than the Embed, I figured it was better if the Embed didn't move from channel to channel

Tested/Compiled On
Windows 10 (Local)
Raspberry OS (Arm64 Local)
Debian 10 (Arm64 and x64 Local)

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
Would it be pushing it to divide the track time by 4 to move the progress bar over time if the Track is Seekable?
I have pondered this since Pre TS Bot Music Controls, and still can't decide if it's pushing API spam territory 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Last Change - Disable the next button on last song or when playing one track
image

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Didn't like how the previous button filter worked, it would say interaction failed to users not in the same voice channel,

now it will send that user an ephemeral message

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
This version works just fine, it really needs to be slimmed down
and I want to add the `options.json` to sorta fill out the rest of the check-list

- Options
```
  {
"playLiveStreams": true,
  "playVideosLongerThan1Hour": true,
  "maxQueueLength": 1000,
  "AutomaticallyShuffleYouTubePlaylists": false,
  "inactivityTime": 30
}
```

I apologize but seems like a good opportunity

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
## Progress
- [x] cleanup PlayerEmbedHandler
- [x] AutomaticallyShuffleYouTubePlaylists (changed to an option in the /play command)
- [x] inactivityTime
- [x] playLiveStreams
- [ ] playVideosLongerThan1Hour
- [ ] maxQueueLength

**Comment by Bacon-Fixation** [comment]
This adds [metadata-filter](https://www.npmjs.com/package/metadata-filter) to the Dependency List
Removes some Extra stuff in the song title like (Official Music Video), (Remastered), (Acoustic Version) etc... 
it can help clean up the Player Embed and reduces the total number of characters for the `/queue` command with large queues


Much Love
-Bacon

**Comment by galnir** [comment]
> This adds [metadata-filter](https://www.npmjs.com/package/metadata-filter) to the Dependency List Removes some Extra stuff in the song title like (Official Music Video), (Remastered), (Acoustic Version) etc... it can help clean up the Player Embed and reduces the total number of characters for the `/queue` command with large queues
> 
> Been Retested
> 
> Much Love -Bacon

Only if I'd known about this npm package before :(

**Review by galnir — APPROVED** [review]
Neat improvements 🚀 
The buttons and embed work smoothly. Runs really well on macOS and Debian

**Pull request merged**
