### PR TITLE
Create COVID-19 stats command

### PR DESCRIPTION
**Pull request by wolf20482**
This is the COVID-19 statistics command created by me. Can you please check this? Thanks.

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
#279

**Comment by wolf20482** [comment]
> Related info
> #279 (previous covid tracker)
> [#388 (comment)](https://github.com/galnir/Master-Bot/pull/388#issuecomment-750951997) Comment about new commands and API wrappers
> 
> > This is the COVID-19 statistics command created by me. Can you please check this? Thanks.
> 
> ```
> const Command = require('discord.js-commando');
> const api = require('novelcovid');
> ```
> 
> Where are the dependencies?
> Errors when you launch the bot `MODULE_NOT_FOUND`
> 
> -Bacon

I thought GitHub will automatically update the package.json when I add new packages?

**Comment by Bacon-Fixation** [comment]
without `novelcovid` being listed in the package.json

will never be downloaded or installed

for people that don't already have the `novelcovid` lib installed 

`npm i -s novelcovid` to save it to the pachage.json file

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
the pr is missing the addition of `novelcovid`  to the package.json file

**Comment by kizule** [comment]
You should add package in package.json and run `npm update` what will update package-lock.json file automaticly.

BTW, this idea sounds good.

**Comment by Bacon-Fixation** [comment]
The pr only contains covid.js and nothing else the package.json was not changed to include `novelcovid` in its dep list

**Comment by Bacon-Fixation** [comment]
`npm i -s novelcovid` to save it to the package.json

[npm doc of the install options](https://docs.npmjs.com/cli/v6/commands/npm-install)

Much Love
-Bacon

**Comment by galnir** [comment]
There's no need to install a dependency for 2 simple API functions, I implemented them myself

**Pull request merged**
