### PR TITLE
Saved queues feature

### PR DESCRIPTION
**Pull request by galnir**
The feature everybody waited for including me

### CODE REVIEW

**Comment by Natemo6348** [comment]
Thank you for making this! So far everything is working.

**Comment by galnir** [comment]
> Thank you for making this! So far everything is working.

There is a bug I'm about to fix

**Comment by Natemo6348** [comment]
Oh ok

**Comment by galnir** [comment]
> Oh ok, also I found one, whenever I try to put all the arguments in to add to playlist, it ignores the URL and asks me for the URL anyway, and when I send the URL, it says I don't have a playlist named (URL)

Can you give an example? The order should be !save-to-playlist playlistname url

**Comment by Natemo6348** [comment]
Screenshot 2020-11-11 at 1 41 12 PM

**Comment by Natemo6348** [comment]
nevermind, i somehow skipped over the playlistname when typing

**Comment by Natemo6348** [comment]
Will you be making the playlists save to a JSON to keep your playlists? I don't wanna have to make the playlists every time I restart my bot lol

**Comment by galnir** [comment]
@Natemo6348 The playlist are saved in a json.sqlite file. Did you install the new dependency?

**Comment by Natemo6348** [comment]
I did restart the bot, that's when I realized that my playlist was gone

**Comment by galnir** [comment]
@Natemo6348 That shouldn't happen, did it create json.sqlite file?

**Comment by Natemo6348** [comment]
It's probably because I'm hosting on Heroku, I don't know if it can write to files or not

**Comment by Natemo6348** [comment]
Ok I found out that the issue is that whenever a Dyno restarts, any data created while it was running will be lost, so a data storage addon is required.

**Comment by galnir** [comment]
> Ok I found out that the issue is that whenever a Dyno restarts, any data created while it was running will be lost, so a data storage/database addon is required. (I think)

When running the bot for the first time after installing quick.db it should create a json.sqlite file which saves all the data. I don't really know why heroku doesn't create that file or deletes it

**Pull request merged**
