### PR TITLE
fix: error on playing youtube playlist link

### PR DESCRIPTION
**Pull request by Akikowo**

### CODE REVIEW

**Comment by galnir** [comment]
Can you explain what you did? 
First of all, the playlist you tried running works for me on 2 machines. Besides that, adding a return statement on line 203 won't change anything because if the query won't satisfy the condition(line 131) it won't enter the if statement

**Comment by Akikowo** [comment]
I knew it, but I can't understand that when I run it thrown an error like above image and by adding return statement on line 203 it doesn't happen.
I used node 12. I'll try again with another node version.

**Comment by galnir** [comment]
What happend there is that your query matched both if statements. It shouldn't enter the second one tho, so my question is did you change anything in lines 206-208?

**Comment by galnir** [comment]
Actually the query does match the second if statement, but nevertheless it shouldn't enter it because of lines 186-202

**Comment by Akikowo** [comment]
I think error come from regex. I tried this regex code ```/^.*(youtu.be\/|list=)([^#\&\?]*).*/``` and it work for me.

**Pull request closed without merging**
