### PR TITLE
Update bot-status.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Ready for Review (no rush)

Rework of #428

Adds - CPU % only for Bot owner
limits other data to only the bot owner

- Bot Owner
image

- Everyone Else
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
Question, would it make sense to also include ping in bot-status or not?

**Comment by galnir** [comment]
> Question, would it make sense to also include ping in bot-status or not?

Great idea
@Bacon-Fixation you can use the code from the 'ping' command that comes with [discord.js-commando](https://github.com/discordjs/Commando/blob/master/src/commands/util/ping.js)

**Comment by Bacon-Fixation** [comment]
on it

**Comment by Bacon-Fixation** [comment]
image

**Comment by Bacon-Fixation** [comment]
Should Ping be visible to everyone ?

**Comment by galnir** [comment]
> Should Ping be visible to everyone ?

Yeah np with that

**Comment by Bacon-Fixation** [comment]
Ping is now available to everyone

image

Much Love
-Bacon

**Pull request merged**
