### PR TITLE
Music Player - Button Controls & Volume Command

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
- [x] Add Volume control
- [x] Create Guild Table in DB (requires re-run of `npx prisma migrate dev`)
- [x] add Album art Thumbnail
- [x] Add Queue Length
- [x] Add `Users` Info into Track Info to show who requested the track with avatar
- [x] 30-second inactivity timer
- [x] Delete Embed at end of song
- [X] Next & Previous track info
- [X]  add button controls
- [X]  Test

Buttons are only usable by members in the same voice channel as the bot
Player embeds are self deleting when song is done or 30 mins has elapsed
you can bring back the buttons with `/now-playing`

Edit: TIL it can also play Twitch(livestream only), and SoundCloud audio sources ...... Nice!

### Current State - YouTube
image

Tested on
Windows 10 (Local)
Raspberry OS 64Bit (arm64/Local)
Debian 10 (Arm64/Local)

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
want to release this before Twitch so i can resolve my self created PR conflicts <3

**Comment by Bacon-Fixation** [comment]
This should be ready for Review

Would like to merge this before #698, As I will need to resolve some self created merge conflicts between these Pr's <3

Note: I am aware that the Players Embed Color may be green after updating from previous version. This is only temporary, it will sort its self out after a few minutes

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@galnir ! have a question, shouldn't the `migrations` folder be added to the `.gitignore` as running the `npx prisma migrate dev`  they are unique to that users DB , if a "migration" were to be added to the repo, and a user were to run `npx prisma migrate dev` after a schema change it will cause a DB mismatch and force the user to wipe the current db to continue


i ran into this when setting up my Raspi Pi's for testing and setup instructions and noticed i had to wipe an existing DB twice

Much Love
-Bacon

**Comment by galnir** [comment]
> @galnir, I have a question, shouldn't the `migrations` folder be added to the `.gitignore` as running the `npx prisma migrate dev` compares the folder names to what is inside the DB. if a "migration" were to be added to the repo, and a user were to run `npx prisma migrate dev` after a schema change it can cause a DB mismatch and force the user to wipe the current db to continue
> 
> i ran into this when setting up my Raspi Pi's for testing and [setup instructions](https://github.com/Bacon-Fixation/Master-Bot/wiki/Raspberry-Pi-Instructions) and noticed i had to wipe an existing DB twice
> 
> Much Love -Bacon

I've read it shouldn't be ignored by Git but in this case it should, so yeah

**Comment by Bacon-Fixation** [comment]
1) sounds like a good idea, I can look into that.

2) I missed that. My bad, I can correct it


Side question have you run into something I'm calling phantom command data. Like if I make a change to a command and restart the bot to load the changes, I will get back the previous version in discord, but console log shows the current version data. I have now run into this a few times now and it makes it difficult to debug when the changes are not represented correctly.
I even went as far as to clear the command list and re-register all the commands (can only do this 3 times in a day cuz of limits) and would still get a Cached version when running the command. Do you have any suggestions on why or to prevent this?


Issues range from bogus "interaction already been replied to" (I removed them all and still got this message), to the Embed data being random( like shortly after updating my pi to this pr the embed colors were green for 2 hours) there isn't any green in this pr. I has me stretching my head

**Comment by Bacon-Fixation** [comment]
- [ ] Player Embed Buttons are a function

currently having to run prototype commands on new Discord Client_id's to make sure no Cached Data
my dev bot (windows), with this pr the embed is still green/blue, i don't know how to fix this on my end, console tells me its `#ff0000`, but it's green/blue, but these PR commands were reloaded dozens of times and its stuck with bogus errors and embed Data

my main(Pi 4 Raspian), it's correct (took few hours to fix its self only had 2 changes to the commands)
the newly created Client_Id's also worked as expected right away (windows)

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Apologies for the last second addition
but noticed stage channels were not accounted for and wellllllllllll i had some fun <3
- Stage Channel Support
image

**Comment by galnir** [comment]
> 1. sounds like a good idea, I can look into that.
> 2. I missed that. My bad, I can correct it
> 
> Side question have you run into something I'm calling phantom command data. Like if I make a change to a command and restart the bot to load the changes, I will get back the previous version in discord, but console log shows the current version data. I have now run into this a few times now and it makes it difficult to debug when the changes are not represented correctly. I even went as far as to clear the command list and re-register all the commands (can only do this 3 times in a day cuz of limits) and would still get a Cached version when running the command. Do you have any suggestions on why or to prevent this?
> 
> Issues range from bogus "interaction already been replied to" (I removed them all and still got this message), to the Embed data being random( like shortly after updating my pi to this pr the embed colors were green for 2 hours) there isn't any green in this pr. It has me stretching my head
> 
> Much Love -Bacon

I'm quite sure adding the guild id in the command registry options solves it:
```
  public override registerApplicationCommands(
    registery: ApplicationCommandRegistry
  ): void {
    registery.registerChatInputCommand({
      name: this.name,
      description: this.description,
      options: [
        {
          name: 'playlist-name',
          description: 'What is the name of the playlist you want to create?',
          type: 'STRING',
          required: true
        }
      ]
    }, {guildIds: ['the id of the guild you are testing in']});
  }
}

```

**Review by galnir — APPROVED** [review]
Really nice work, tested it and it works well 💯 
It would be even better if you could find a way to disable or remove the buttons if a user uses /leave instead of hitting a button, but no pressure on that, maybe I will do it myself

**Comment by Bacon-Fixation** [comment]
currently it should delete an open Player Embed when a button is pressed after the music player has been disconnected, i had to or i would get a console error

i can look into actively deleting the message when /leave, /Skip, /Skipto commands are used

Much Love
-Bacon

**Pull request merged**
