### PR TITLE
Reaction-Control

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Addressing #371
Used pagination embeds to make a simple reaction controls for play and nowplaying commands 

would love feedback <3
image

Add Links to display-playlist and queue commands
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
This looks good so far, I can't wait for the finished product

**Comment by Bacon-Fixation** [comment]
Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Should be ready

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Testing in progress
Windows 10 - works
Debian 10 - works
Raspberry Pi OS 10 - works
CentOS7
repl.it
glitch.com
Heroku


Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Testing in progress
Windows 10
Debian 10
Raspberry Pi OS 10 
CentOS7
repl.it
glitch.com
Heroku

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I apologize just realize this was not a Draft

**Comment by ModoSN** [comment]
Nice work!

**Comment by Bacon-Fixation** [comment]
That should be that last tweak needed
Now its down to Testing :D

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Closing to reopen so all of these commits don't flood the history with commits it should be ready

Much Love
-Bacon

**Pull request closed without merging**
