### PR TITLE
Create role-info.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Addressing #449 Role Information command 

Displays Role information like ID number, Creation Date, Permission List, and the members who have it

Use the role tag, role ID, or role name Example `!role-info admin`

- Basic Info
image

- Permissions List
image

- Member List
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
Wow this looks amazing, and it has exactly what I need

**Comment by Natemo6348** [comment]
@Bacon-Fixation idk why, but when I use the command, it only says I have the role when in fact more people have the role, any idea why?

**Comment by Natemo6348** [comment]
seems like it only happened in one server so far, so idk what's causing it

**Comment by Natemo6348** [comment]
it seems to only be detecting me for any role for some reason

**Comment by Bacon-Fixation** [comment]
@Natemo6348 
in the discord Dev portal there is 2 Intent Settings make sure they are enabled to allow the bot to see the entire member list of a server
image

once you save your changes in the Dev Portal restart your bot in order for the changes to be sent

**Comment by Bacon-Fixation** [comment]
for some reason around Oct Discord changed some things when it comes to Events and Server Member lists

without server member intnet you can only see members that have messaged in the server

Much Love
-Bacon

**Comment by Natemo6348** [comment]
oh sorry, i thought i had enabled those already, thanks

**Comment by Bacon-Fixation** [comment]
I'm not sure if it just a coincidence but, I had that same thing. I'm pretty sure I enabled them a long while ago, but yesterday they were off when I was testing the welcome message yesterday 

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation I'm currently rewriting some code(attempting to write code in a more functional way), I promise I'll take a look at this PR asap

**Comment by Bacon-Fixation** [comment]
No worries my friend, :D 

Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Thanks for taking care of #449 :)

**Pull request merged**
