### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Status: Ready

Post Edited 08/15/22

<strike>(literally struggling to convey the steps for a Readme.md without sounding confusing)</strike>

here is my attempt to update the docker-compose.yml and dockerfile <3 (Still new to docker), 
this should have everything Lavalink/Redis/Postgres all bundled ready to go 

 ### Minimum Needed changes
changes to `config.json` portion of the readme.md for docker
```
  "lava_host": "lavalinkDocker",
```
`.env`
rename `.env.example.docker` to `.env`

then run 
`docker compose -f "docker-compose.yml" up -d --build`
 this will make all the containers and start master-bot

### Extra options for Advanced use
users can edit `.env` to change the credentials to their liking (not needed but, the option is there)
<strike>**`docker-compose.yml`, `config.json`, and `.env` credentials must match**</strike> 

Full `.env` additions for customization if wanted for both docker and non docker usage (addresses #735)
```
 REDIS_HOST="redisHost" 
 REDIS_PORT=6379
 REDIS_PASSWORD="redisPassword" 
 REDIS_DB=0
```

### Left to do

- [x] Update Testing (ie. does changes to schema cause an error during `compose up`  when updating an existing postgres container)
- [x] Log possible errors and resolutions (For better troubleshooting and assistance)
- [x] include the dashboard as an option (opened port 1212 for Dashboard use)
- [x] Readme.md edits 
- [X] <strike> pi install instructions edits </strike> (can just reference the README steps for docker, works on either)  

### Cross Compatibility Bugs to fix
- [x] Add and register a font for Canvas to use for Games command

[a2a8fe5](https://github.com/galnir/Master-Bot/pull/738/commits/a2a8fe5633d75de66c47a263ea047b3bcfdcd396) Tested on
| OS 	| Arch 	| Postgres 	| Redis 	| Lavalink 	| Dashboard 	|
|---	|---	|---	|---	|---	|---	|
| Windows 10/11 	| x64 	| Docker	| Docker 	| Docker 	| Localhost 	|
| Debian 	| Arm64  Pi 3/4	| Docker 	| Docker 	| Docker 	| Localhost 	|
| Ubuntu 	| Arm64 Pi 3/4	| Docker 	| Docker 	| Docker 	| Localhost 	|
| Debian 	| x64 	| Docker 	| Docker 	| Docker 	| Localhost 	|
**Raspian OS 64 cannot use docker compose**

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
please please please someone correct me on this if i am wrong, by no means am i knowledgeable on the subject of db security. 

Currently, when the containers are created they are linked through dockers internal network utility to each other (postgres/redis/lavalink) and dont accept outside connections.
The question is, is it ok to use the postgres default username and pass in this instance ?

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation I'm pretty sure @kfirmeg knows the answer to that, so we'll wait for his reply

**Comment by kfirmeg** [comment]
From my experience with docker, the containers that are created really aren't connected to the outside network by default without mapping their ports to ports on the host network. It should be fine to leave it on default, and if users want to change it then they can always change it in the .env file.

**Comment by Bacon-Fixation** [comment]
Sweet, Ty so much for the replies,

I did move the Postgres and Redis variables to the .env and changed the docker-compose to use them to set up the containers 
and edited the `.env.example` do have a quick set up using docker if wanted

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
in sticking with the theme ease of use 

change `"lava_host": 0.0.0.0` to `"lava_host": "lavalinkDocker"` in `config.json` 

rename `.env.example.docker` to `.env`

then run `docker compose -f "bot\docker-compose.yml" up -d --build`

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
its my attempt to make the core and related services of master bot easier to get going using docker

this should be good to go

Much Love
-Bacon

**Comment by galnir** [comment]
I'm not merging this yet because there's something I'm working on that would require some changes to this if I manage to get it done right

**Comment by Bacon-Fixation** [comment]
No worries, i noticed the branch (been playing around with it <3 learning as i go)

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation That branch is dead unfortunately :( I have another locally that is the one to go. Got tRPC to work end to end with few issues that I'm hoping to solve tomorrow

**Comment by Bacon-Fixation** [comment]
Nice!!!, cant wait

**Comment by Bacon-Fixation** [comment]
been playing around that new one too 
it runs nice and (Dashboard message) "hi" back btw :D
i like the challenge, and hope to have a PR for those additions  

filled in the Guild table manually with `npx prisma studio`
for testing purposes.

Much Love
-Bacon

**Comment by galnir** [comment]
> been playing around that new one too it runs nice and (Dashboard message) "hi" back btw :D i like the challenge, and hope to have a PR for those additions
> 
> filled in the Guild table manually with `npx prisma studio` for testing purposes.
> 
> Much Love -Bacon

You can clear the tables, kick the bot out of the guild and invite him - it should add you and the guild to the db
Assuming you're on the latest commit

**Comment by Bacon-Fixation** [comment]
Closing for updated version of this pr using the new changes 

Much Love
-Bacon

**Pull request closed without merging**
