### PR TITLE
add queue history (ability to play from history) feature #531

### PR DESCRIPTION
**Pull request by galnir**
#531

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
im not sure if this is supposed to happen but i tryed to play a song from history but the bot never joined the channel 

image

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation For some reason I forgot to write this use case -_-

**Comment by Bacon-Fixation** [comment]
curious what happens if a saved playlist is named `1` or the other numbers (do both messages come up, if so if you press `1` does it play the playlist or the queue-history?)

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@galnir 

the following updates the interactive embed with a back button when a queue history is present

you can add this to line 851 (didn't want to just commit to the PR and cause issues) 
```
  if (message.guild.musicData.queueHistory.length > 0) {
    videoEmbed
      .addField(
        '⏮️ Previous Song',
        `
    [${
      message.guild.musicData.queueHistory[
        message.guild.musicData.queueHistory.length - 1
      ].title
    }](${
          message.guild.musicData.queueHistory[
            message.guild.musicData.queueHistory.length - 1
          ].url
        })`
      )
      .addFunctionEmoji('⏮️', function(_, instance) {
        if (!message.guild.musicData.songDispatcher) return;

        instance
          .setDescription(songTitle + playbackBar(message.guild.musicData))
          .setTitle('⏮️ Previous Song')
          .setTimeout(100);

        message.guild.musicData.queue.unshift(
          message.guild.musicData.queueHistory[
            message.guild.musicData.queueHistory.length - 1
          ]
        );
        playSong(message.guild.musicData.queue, message);
        if (message.guild.musicData.songDispatcher.paused)
          message.guild.musicData.songDispatcher.resume();
        message.guild.musicData.loopSong = false;
        setTimeout(() => {
          message.guild.musicData.songDispatcher.end();
        }, 100);
      });
  }
```

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I apologize for the ping, realized my deleted suggestion was flawed

Again my apologies 

Much Love
-Bacon

**Comment by galnir** [comment]
> I apologize for the ping, realized my deleted suggestion was flawed
> 
> Again my apologies
> 
> Much Love
> -Bacon

I've read your deleted suggestion, open a PR after this one gets merged
Also please test and review this PR after the recent commit :)

**Comment by Bacon-Fixation** [comment]
Works great for me 💯 

ran out of things to break it :D

Much Love 
-Bacon

**Pull request merged**
