### PR TITLE
Assign role to specified member.

### PR DESCRIPTION
**Pull request by muhitrhn**
This command helps the guild owner to simplify the role adding feature of discord. It help guild owners to easily assign a role to a user which will be really helpful in case of guild management.

### CODE REVIEW

**Comment by muhitrhn** [comment]
May i close the pull requests if not mandatory @galnir ?

**Comment by Natemo6348** [comment]
i'd like to point out that in [#477](https://github.com/galnir/Master-Bot/issues/477#issuecomment-803429609) galnir said that they are not adding new features right now, so it may be a while

**Comment by galnir** [comment]
I'll review this PR soob

**Review by Natemo6348 — COMMENTED** [review]
I think you should add the alias 'add-role', also why make it owner only?

**Comment by muhitrhn** [comment]
> I think you should add the alias 'add-role', also why make it owner only?

Okay, i will add the alias. And made it owner only on my bot. Just copied and pasted it. Instead, i think i should allow only administrators to run this command?

**Comment by Natemo6348** [comment]
yeah maybe, or at the very least people with manage roles permission

**Comment by galnir** [comment]
I have some changes to make I can't apply since you deleted the fork. I'll merge this and apply them afterwards

**Comment by muhitrhn** [comment]
Okay!

**Pull request merged**
