### PR TITLE
update mute.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Original Command Work and Code by Natemo6348 
Request from PR #304 

Added error messages and no longer gives the `TypeError: Cannot read property '0' of null` error when entering an invalid username or id

image

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
this is exactly what i wanted thanks!

**Comment by Natemo6348** [comment]
at the catch at the end i added for it to say a muted role hasn't been created yet, which isn't needed now since it has it's own now

**Comment by Bacon-Fixation** [comment]
Changed catch message to a General error and lets the Info go to the Console

**Comment by galnir** [comment]
What if you want to unmute a user?

**Comment by Natemo6348** [comment]
I can definitely work on that

**Review by galnir — APPROVED** [review]

**Pull request merged**
