### PR TITLE
Added Vote/Poll Commands

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
was a request so that we can quickly make Polls and Vote to let discord members pick his next game to stream.
but it can be used for anything really

- **Fixed and Stable**
Vote poll

as always tested on windows 10

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
just realized i used the older RichEmbed will reopen once corrected

**Comment by Bacon-Fixation** [comment]
wouldn't let me reopen for some reason....... got hung up trying to reload the page may have something to do with the weird commit issue i ran into this morning 
will make sure its a cleaner in the future(once i figure out what happened)
was a current fork(deleted/recreated fork with current)
when i started the project this morning
all i did was push a commit to the PR and it merged twice and then commited my change

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
i still had a bug that Crashes the Bot when the Timer runs out 

i used `fetchMessege()` incorrectly  and didn't have time to test the Timer
so i have removed it temporarily
to prevent the crash  

i apologize this was a complete failure on my part

Much Love
-Bacon

**Comment by galnir** [comment]
I'll keep this open until we're confident it's stable

**Comment by Bacon-Fixation** [comment]
Fixed and operates without Failure 

Much Love
-Bacon

**Comment by galnir** [comment]
I'll test it myself aswell, great command idea 🥇

**Comment by Bacon-Fixation** [comment]
I'm done with this one.

I apologize for the constant changes
but this is done done done done I swear

Much Love
-Bacon

**Review by galnir — CHANGES_REQUESTED** [review]
There's an issue I noticed in the vote command. If you attempt to:
```!vote "this is a test123123" 1
It will throw:
```The description must be between 10 and 200 characters in length.```

**Comment by Bacon-Fixation** [comment]
yeah strange i got that too on this commit but when i use `!vote "this is a test"` it does work

**Comment by Bacon-Fixation** [comment]
Interestingly 
`?vote "will you please work?" "NEVER WILL YOU FILTHY HUMAN" 10` works fine
However
`?vote "will you please work?" NEVER WILL YOU FILTHY HUMAN 10` doesn't work, `desc` content is just 'NEVER' which is 5 in length but with quotes `desc` content is 27 in length when the command is entered as a single message .... I'm tearing my hair out tbh 
image
and neither will `?vote "will you please work?" 10` it runs through `desc` and sees a length of 2 and again it will fail

**Comment by Bacon-Fixation** [comment]
Removed the description arg. If there were 2 optional args you had to have 1 or all 3 args of the vote command.
This is not ideal because it limits usability and is a bit confusing to use

Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Great job with these commands 👍

**Pull request merged**
