### PR TITLE
Added function to include announcement channel.

### PR DESCRIPTION
**Pull request by muhitrhn**
I hope this helps! Can you please check @galnir ?

### CODE REVIEW

**Review by galnir — CHANGES_REQUESTED** [review]
Few comments:
1. Instead of the 'if' statement in line 40 and the else statement, you can simply change the argument type of announcementChannel (line 17) to 'channel'. It will not let the user enter an argument that isn't a valid channel on the guild.
2. You forgot to add announcementChannel in line 29.
3. Are you using the bot's prettierrc file? Your spacing isn't the same as the other files' spacing.

Please make sure to test it before committing your changes :)

**Comment by muhitrhn** [comment]
> Few comments:
> 
> 1. Instead of the 'if' statement in line 40 and the else statement, you can simply change the argument type of announcementChannel (line 17) to 'channel'. It will not let the user enter an argument that isn't a valid channel on the guild.
> 2. You forgot to add announcementChannel in line 29.
> 3. Are you using the bot's prettierrc file? Your spacing isn't the same as the other files' spacing.
> 
> Please make sure to test it before committing your changes :)

Oh, those are mistakes! 
Btw, i don’t know why, but the code works like this too!

**Comment by galnir** [comment]
I removed a bunch of unneeded code (explained why in the commit description). I'm not merging this pull request yet because I suspect people might get confused about the channel_name argument, in a sense that why not just send the message in the wanted channel in the first place

**Review by galnir — APPROVED** [review]
Thanks for your contribution @muhitrhn , I also didn't know there's a 'channel' type for arguments which allowed us to remove the code that checks if the provided channel exists

**Pull request merged**
