### PR TITLE
Tweaks and Improvements

### PR DESCRIPTION
**Pull request by PhantomNimbi**
* Create `anime.ts`
 * Create `baka.ts`
 * Create `gif.ts`
 * Create `jojo.ts`
 * Create `gintama.ts`
 * Update `LavaLink` to use `Repl.it` for better audio quality on lower performance systems
 * Update `README.md` accordingly

### CODE REVIEW

**Review by galnir — CHANGES_REQUESTED** [review]
You forgot to rename the class names to AnimeCommand and BakaCommand (from CatCommand).

The replit example is great and would help many folks who have low end pcs or slow internet connections, but I would add it as an alternative to hosting Lavalink locally (maybe as a wiki article?)
Looking at it now I should add a property for the Lavalink port in config.json instead of doing it manually in ExtendedClient.ts

**Comment by PhantomNimbi** [comment]
> You forgot to rename the class names to AnimeCommand and BakaCommand (from CatCommand).
> 
> The replit example is great and would help many folks who have low end pcs or slow internet connections, but I would add it as an alternative to hosting Lavalink locally (maybe as a wiki article?) Looking at it now I should add a property for the Lavalink port in config.json instead of doing it manually in ExtendedClient.ts

will fix thos right now. thanks for notifying me

**Comment by PhantomNimbi** [comment]
There ya go, class names are fixed =)

**Comment by PhantomNimbi** [comment]
> You forgot to rename the class names to AnimeCommand and BakaCommand (from CatCommand).
> 
> The replit example is great and would help many folks who have low end pcs or slow internet connections, but I would add it as an alternative to hosting Lavalink locally (maybe as a wiki article?) Looking at it now I should add a property for the Lavalink port in config.json instead of doing it manually in ExtendedClient.ts

I can probably add that in, should be simple enough =)

**Comment by PhantomNimbi** [comment]
Ok, I believe I made all the necessary updates to get everything in an acceptable feel.

# Changelog

 * Updated Instructions with new guides
 * Update LavaLink to grab both port and secure status from `config.json`
 * Fixed the class names for the gif commands

Let me know if there's anything else you would like me to do.

**Review by PhantomNimbi — COMMENTED** [review]
All files have been fioxed

**Comment by PhantomNimbi** [comment]
Minor typos fixed

**Comment by PhantomNimbi** [comment]
Added public LavaLink server instructions for those who don't want to host their own LavaLink server. Working perfectly.

**Review by KiyoshiKunCool — COMMENTED** [review]
You should add this link for someone who need to grab a free public lavalink :3

Link: https://lavalink.darrennathanael.com/

**Comment by PhantomNimbi** [comment]
> You should add this link for someone who need to grab a free public lavalink hosting :3
> 
> Link: https://lavalink.darrennathanael.com/

Will do. I actually got the one I  included in the instructions from there =)

**Comment by PhantomNimbi** [comment]
Updated the README to make things a bit cleaner and more organized.

# Changelog

 * Commands moved to `commands.md`
 * Resources moved to guides

**Comment by PhantomNimbi** [comment]
> There are too many commits here
> 
> 1. The replit alternative instructions should be on the wiki and the README should link to it (same applies to everything under guides/). I'll give you an access to the wiki folder now
> 2. Open a new PR for the gif commands
> 3. Open a new PR that modifies the README so it links to the replit wiki articles

ok will do =)

**Comment by PhantomNimbi** [comment]
> There are too many commits here
> 
> 1. The replit alternative instructions should be on the wiki and the README should link to it (same applies to everything under guides/). I'll give you an access to the wiki folder now
> 2. Open a new PR for the gif commands
> 3. Open a new PR that modifies the README so it links to the replit wiki articles

Done

* #682 
* #683 
* #684

**Pull request closed without merging**
