### PR TITLE
2 Player Game of Connect 4

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
No image files required all assets are created through canvas

you can get the rules by typing `!help connect4`

- Example `!connect4 bacon`
image

- Notes
enabling server member intent (in discord dev portal) is recommended for this command to guarantee the ability to grab the requested player2 data.
without server member intent, the requested player2 must have already sent a message since the bot has been online, you can use mentions to get around this quirk

### Tested On
- (Local Hosts)
 Windows 10
 Debian 10
Raspi OS 10

- (Web Hosts)
Heroku
Glitch.com
Repl.it

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
Oh my god, I love this and I haven't even used it lol. I've been looking for ways to add games to this, but couldn't figure it out

**Comment by Bacon-Fixation** [comment]
:D it was a blast to work on

**Comment by Natemo6348** [comment]
I could try to look at it and see if I could figure it out

**Comment by Bacon-Fixation** [comment]
ty <3
it didn't seem to matter if i left the game image in the channel or delete it imediatly like am now 
every once in a while the embed image is not there :D

discord never actually deletes things so deleteing it after creation just for the URL works well
i did try creating a temp text channel to dump the images during a game then deleteing the temp text channel (this smoothed out the transition between turns) but still the same quirk (no board image)

Much Love
-Bacon

**Comment by galnir** [comment]
What a great idea! I'll probably review it this weekend

**Comment by Bacon-Fixation** [comment]
Those are the last tweaks

embed color changes to also indicate player in play.
at the end of the game the embed Color, Thumbnail, and Title change to the Winner of that match

image

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
i want to add the [negaMax algorithm](https://en.wikipedia.org/wiki/Negamax#:~:text=From%20Wikipedia%2C%20the%20free%20encyclopedia,implementation%20of%20the%20minimax%20algorithm.) to this command sometime in the future, so that here is a CPU opponent for single player mode

Much Love
-Bacon

**Comment by galnir** [comment]
> ### Brain Storming
> * possibly add the [negaMax algorithm](https://en.wikipedia.org/wiki/Negamax#:~:text=From%20Wikipedia%2C%20the%20free%20encyclopedia,implementation%20of%20the%20minimax%20algorithm.) to this command sometime in the future, so that there is a CPU opponent for a single player mode
> * possibly add a shadow layer (in canvas) for a 3d effect
> * possibly use players avatar(if available) as the Pieces on the board
> * possibly add a leaderboard
> * possibly add personal stats (win%, lose%, total games, etc...)
> 
> these are just some ideas for future updates or if someone wanted to tackle them and not planned for this PR
> 
> Much Love
> -Bacon

After I review and merge this PR we should definitely open an issue for that

**Comment by Natemo6348** [comment]
Also I saw this while searching around, there is a npm package called connect4-ai that you might be able to use

**Comment by Bacon-Fixation** [comment]
I apologize for delays, but this should be ready now for review (no rush <3)

also the board is now locked when a winner is determined

Much Love
-Bacon

**Comment by galnir** [comment]
I tested the game today and ran into an issue in my first game:
Screenshot_1

The last turn was me placing a red disc in column 7 and there was no indication of me winning, the game got frozen meaning there was no option to place any more discs

Also player 2 is my opponent not me
No error in console aswell

**Comment by Bacon-Fixation** [comment]
Roger that, i will look deeper into the Embed no always updating, i want to eliminate the need for the 🔄 button (if possible)

Much Love
-Bacon

**Comment by galnir** [comment]
> Roger that, i will look deeper into the Embed no always updating, i want to eliminate the need for the 🔄 button (if possible)
> 
> Much Love
> -Bacon

Screenshot_2

Also this happened, I won and it let my opponent place a disc and then it also let me place a disc until I won(placed a disc in column 2)

**Comment by galnir** [comment]
I've narrowed the issue down to the 3rd line from the bottom
Screenshot_3

**Comment by Bacon-Fixation** [comment]
Found it! 
the `gameBoard` array was 90* CCW to the Board Image leaving (column 7) blind to `checkWinner()` entirely


- retest of that spot 
image

- game of me losing :D
image

Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Incredible work, kudos to you Bacon

**Pull request merged**
