### PR TITLE
Docker-Compose

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Post Updated 8/31/2022
Docker compose Implementation

there is a premade `docker.env`(editing it is not required, but the option is there), that will override the Prisma, and Lavalink variables to make everything happy and simple to deploy all the supporting services and Master-Bot

### How to use

example below is start to finish for getting all the services and master-bot going (postgres/redis/lavalink/dashboard)

- install Docker Desktop
- create your `application.yml` file
- fill out your `.env` file as normal
- run `docker compose --env-file docker.env up -d --build` in root folder
- enjoy

### How to handle Master-Bot updates

if the containers are already made and there has been an update to Master-Bot

- clone/pull repo
- run `docker compose --env-file docker.env up -d --build` <br>
  Also addresses #735
  the following can be added to the `.env` if they wish to use them (not required)

```
 REDIS_HOST="redisHostPath"
 REDIS_PORT=6379
 REDIS_DB=0
 REDIS_PASSWORD="redisPassword"
```

Side Note

- you can expose port "5555:5555" in the "docker-compose.yml" then run `npx prisma studio` inside the bot's docker container to manage the Database with a nice web interface at localhost:5555
- Bot logs are outputted to the `./logs/` folder (outside of container) for debugging

### **Updated** Test Results ([a07b25b](https://github.com/galnir/Master-Bot/pull/742/commits/a07b25bd9303b158f921f38da7853c74655f10aa))

| **OS**        | **Arch** | **Nodejs** | **Docker** | **Compose**                                                                                      |
| ------------- | -------- | ---------- | ---------- | ------------------------------------------------------------------------------------------------ |
| Windows 10/11 | x64      | pass       | pass       | supported                                                                                        |
| Debian        | x64      | pass       | pass       | supported                                                                                        |
| Raspian 64    | Arm64    | pass       | pass       | [unofficial support](https://www.jfrog.com/connect/post/install-docker-compose-on-raspberry-pi/) |
| Debian        | Arm64    | pass       | pass       | supported                                                                                        |
| Ubuntu 21.10  | Arm64    | pass       | pass       | supported                                                                                        |
| Manjaro       | Arm64    | pass       | pass       | unofficial support (arch install)                                                                |

All Arm64 Tests were done on a Pi4b 4, 6, and 8 gig models,

Note: 4gig model dosen't have enough ram to run all services and master-bot containers, so i recommend 6gigs or higher if you decide to go that route

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
you can also copy the contents of `docker.env` and paste at the bottom of the `.env` and run `docker compose -d --build`
caveat when editing, is that the postres info must match the DATABASE_URL link and all 3 HOST variables must be the service names
```
LAVA_HOST="lavalink"
POSTGRES_HOST="postgres"
REDIS_HOST="redis"
DATABASE_URL="example:text@postres:5432........."
```

**Comment by Bacon-Fixation** [comment]
Sorry to converting to draft, found a bug with Prisma + Docker on arm64 systems(i assume issue is present on mac arm64), and need to test other Nodejs versions like "slim" or "base" for better compatibility instead of "alpine",

```
 => ERROR [6/6] RUN ["npx", "prisma", "generate", "dev"]                                                                                                                                                                                                                                                                                                                                                                                        8.1s
------
 > [6/6] RUN ["npx", "prisma", "generate", "dev"]:
#0 7.885 Error: Unknown binaryTarget linux-arm64-openssl-undefined and no custom engine files were provided
------
failed to solve: executor failed running [npx prisma generate dev]: exit code: 1
```
 
i apologize for the sudden change,

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation Do I need to edit anything related to the DB before running compose? I'm getting 
```
Can't reach database server at `postgres`:`5432`

Please make sure your database server is running at `postgres`:`5432`.

Error: P1001: Can't reach database server at `postgres`:`5432`
```

**Comment by Bacon-Fixation** [comment]
Shouldn't need to @galnir,
is this on mac?
Are all the containers being built ?  
And did they report a status ?

Running the docker compose command with the `docker.env ` should do all of that for you during creation and starting all the containers as a cluster
with `docker compose --env-file docker.env up -d --build`


try adding/replacing the variables in the `docker.env` into your `.env` 
and just run `docker compose up -d --build` in the root folder instead

Order of events should be
- build master-bot/dashboard image, 
- then create/start service containers(lava/redis/postgres),
-  wait for "ready" status return from the service containers,
 - then update db containers schema,
 - then start/create the master-bot/Dashboard container (uses `npm run dev` to build and run)
 

Much Love
-Bacon

**Comment by galnir** [comment]
Okay so for some reason adding 300ms timeout solves the issue on Mac. Besides that I'm going to use a cloud Postgres db because testing on different machines requires me to re-invite the bot to the guild on new dbs. Heroku recently announced they're killing their free tier so I'll have to find a better solution (Planetscale is awesome but I use it on another project and they allow 1 free db, check it out)

**Comment by Bacon-Fixation** [comment]
For testing i've been adding an upsert with my test server and user data pre-filled inside the `client.on("ready"` block of bot/src/index.ts to switch between systems quickly, this avoids having to kick the bot every switch

Much Love
-Bacon

**Comment by galnir** [comment]
Okay so it works both on Windows and Mac, I ran into an issue with Postgres and turns out that if you run the bot using Docker you need to delete or comment out the DATABASE_URL variable.

**Review by galnir — APPROVED** [review]
Works like a charm on Mac and Windows, I'll write a short guide in the README on how to get it running right (comment out DATABASE_URL in env)

**Pull request merged**
