### PR TITLE
Chat Gpt Command working

### PR DESCRIPTION
**Pull request by Ka1-S**

### CODE REVIEW

**Comment by Ka1-S** [comment]
I made a command where it uses chatgpt, sorry for the 20 commits, please ignore

**Comment by Bacon-Fixation** [comment]
Howdy @Ka1-S, I hope you don't mind that I remade your PR, it seems that this one includes way more than just the chatGPT command, and I just boiled it down to only the ChatGPT command.
Also a couple of revisions other than moving it to English (also looking into localizations)
Deferred the Reply, then edited the reply when response was received,
not include the command to the registry if `OPEN_API` is missing from the `.env`

Much Love
-Bacon

**Comment by Ka1-S** [comment]
I made some small changes so that it splits the message block into two if the request to the chat GPT is greater than 2000 characters, which is the maximum that a Discord bot can send. So, I made a new PR. Sorry, I don't know how to fix my PR to include only the CHAT PT command. I have already translated it into English to reduce the necessary changes. Thank you very much, BACON <3.

**Comment by Ka1-S** [comment]
I made some small changes so that it splits the message block into two if the request to the chat GPT is greater than 2000 characters, which is the maximum that a Discord bot can send. So, I made a new PR. Sorry, I don't know how to fix my PR to include only the CHAT PT command. I have already translated it into English to reduce the necessary changes. Thank you very much, BACON <3.

**Comment by Bacon-Fixation** [comment]
Added your changes to the #788

not exactly sure how to remove the other 100 file changes from this PR, so I have just been moving your changes to a clean PR, I hope you don't mind

re-included the deferReplay() and editReply() for the first message if response is over 2000 characters or if the response was under 2000 characters, to remove `The application did not respond` message that appears above commands response

Much Love
-Bacon

**Comment by galnir** [comment]
I'm closing this for #788 but @Ka1-S the credit is all yours

**Pull request closed without merging**
