### PR TITLE
Reminder Command Redis Edition

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Post Updated 9/24/2022

a Rework of #728 to use Redis TTL

## Function
when bot is started, the reminders Table from Postgres is cached to redis and refreshed once a day (also checks for stale reminders that may still be in the Postgres DB due to a possible missed trigger event and either remove them or set up for the next alarm)
uses Redis TTL and a keyspace event listener to trigger the notifications.
uses Direct Messages to function, and was designed to be personal reminders, so most of the responses are ephemeral.
You can set reminders by Text Channel or Direct Message. 
All reminders are Direct Messages (can't annoy other people)
if it had a repeat options, then create a new db entry when message is sent (or during clean up check at start up or daily check)

## Caveats
- <strike>Reminders being deleted when the Redis Server is Hosted on an Ephemeral Web Services like Heroku </strike> ( resolved in [9833b67](https://github.com/galnir/Master-Bot/pull/753/commits/9833b67bc86e5d8811ef0e83c82dd49a7c4367c8) )
- Doesn't account for Daylight Savings Time (just resave your timeOffset with `/reminder save-timezone`)

## Objectives
- [x]  Convert to Redis TTL
- [x]  Sub Commands View/Set/Remove/Save-timezone
- [x]  Small input chain - Minimum of 2 Inputs to set a reminder `event` and `time`
- [x] TimeZones - Get users Timezone offset by asking for Local Date and Time
- [x] Repeat options - "daily", "weekly", "yearly", "monthly*"
- [x] Compatible with Pi (arm64) 
- [x] Compatible in dockerized containers (need additional `.env` variable `TZ=<tz-database-name>` when using Docker Only)
- [x] DB maintenance - Checks (at launch and every 24 hours) and remove stale/old Reminders from Postgres, if reminder had a repeat option selected, then recreate reminder for the need time

*Monthly option can only be used if the desired Day is less than the 28th

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
My apologize progress has been slower than I expected, and will only commit functional iterations after basic testing
and may not be compatible with other systems until final release, 
[2759cb8](https://github.com/galnir/Master-Bot/pull/753/commits/2759cb8fa0975ed663564e25dfcd1ee0e0146eab) functions but has Bloat and Needs a `TZ` variable in the `.env` when using Docker to function correctly (docker will set the correct time but not the timezone at build),

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Testing has started, running it for a bit longer before requesting a review, my apologizes for the delays in the dev .......... time is rough to deal with

`TZ=<bot-time-zone>` is **required** in the `.env` for Docker implementation of master-bot or all time will be off by double

Much Love
-Bacon

**Comment by galnir** [comment]
Sorry bout the timing but the routers will need to get updated to tRPC v10 when I merge #760 (just need to test it a bit more) 😶‍🌫️

**Comment by Bacon-Fixation** [comment]
Sweet, sounds good

**Comment by Bacon-Fixation** [comment]
Closing for the TRPC v10 PR

**Pull request closed without merging**
