### PR TITLE
Patch for TwitchStatus

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
This fixes an Error and README mismatch (  "twitchToken" to "twitchClientSecret")

- Tested
Windows 10
Ubuntu
Raspberry OS 10
and thank you galnir for having the patience of a saint <3 

Much Love
-Bacon

### CODE REVIEW

**Comment by galnir** [comment]
If you read the simple-twitch-api code on GitHub you'll see it's basically does the same as my code. I'm trying to think why you're getting an error

**Comment by Bacon-Fixation** [comment]
If I remove simple-twitch-api and clone fresh 
and do a `npm i` with current package
`node .`
then try `!twitchstatus`
I get the error it didn't matter which system I tried

**Comment by galnir** [comment]
> If I remove simple-twitch-api and clone fresh (new user situation)
> and do a `npm i` with current package
> `node .`
> then try `!twitchstatus`
> I get the error it didn't matter which system I tried

simple-twitch-api is no good anyway because you can crash the bot by passing weird letters to the command. I'm trying to find out why it doesn't work for you(and any new user) with my method implementation

**Comment by Bacon-Fixation** [comment]
something else is installed with simple-twitch-api

**Comment by Bacon-Fixation** [comment]
@galnir Double confirmed that simple-twitch-api need to be installed in order to work with internal API

**Comment by galnir** [comment]
> @galnir Double confirmed that simple-twitch-api need to be installed in order to work with internal API
> 
> has supporting stuff that is installed
> 
> Error is for Online Embed only Offline works without simple-twitch-api
> 
> image
> trying to provide as much about the issue as i can

I don't have it installed, I also updated my dependencies to their latest versions and it works

**Comment by Bacon-Fixation** [comment]
same but online gives me errors

**Comment by galnir** [comment]
> Same I cloned 10 minutes ago but online gives me errors
> it sends user.data[0] correctly before the onlineEmbed
> when i add to onlineEmbed console.log(user.data[0])
> it sends user.data[0] = blank
> 
> but with simple-twitch-api both embeds work

Can you pull the latest changes and tell me if it still doesn't work?

**Comment by Bacon-Fixation** [comment]
it didn't work with the commit you just posted either
image

**Comment by Bacon-Fixation** [comment]
simple-twitch-api does install 36 packages with it 

image

```
  "asn1": {
      "version": "0.2.4",
      "resolved": "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz",
      "integrity": "sha512-jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==",
      "requires": {
        "safer-buffer": "~2.1.0"
      }
    },
    "assert-plus": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz",
      "integrity": "sha1-8S4PPF13sLHN2RRpQuTpbB5N1SU="
    },
    "aws-sign2": {
      "version": "0.7.0",
      "resolved": "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz",
      "integrity": "sha1-tG6JCTSpWR8tL2+G1+ap8bP+dqg="
    },
    "aws4": {
      "version": "1.11.0",
      "resolved": "https://registry.npmjs.org/aws4/-/aws4-1.11.0.tgz",
      "integrity": "sha512-xh1Rl34h6Fi1DC2WWKfxUTVqRsNnr6LsKz2+hfwDxQJWmrx8+c7ylaqBMcHfl1U1r2dsifOvKX3LQuLNZ+XSvA=="

**Comment by galnir** [comment]
@Bacon-Fixation I just tested twitchstatus.js(as on master branch right now) on a vps that is running debian and it works. 
simple-twitch-api is a package that contains methods. Each method calls a different endpoint of the twitch API. All you do by installing the package is using whatever method you need. I implemented only the methods we need myself internally so we don't need to install this package. According to the [simple-twitch-api json file](https://github.com/alexandrecoulay/simple-twitch-api/blob/main/package.json), its only dependency is 'request', which we don't need because we have node-fetch.
I honestly don't know why you're getting this error because the methods I wrote and the methods the simple-twitch-api guy wrote are basically identical in their behaviour, All they do is request data from an API. 
Btw you should enter ```npm uninstall simple-twitch-api```, not ```npm remove``` (I've never seen ```npm remove``` used so maybe it doesn't uninstall the dependency entirely)

**Comment by galnir** [comment]
@Natemo6348 Is the new twitchstatus command working for you? With the changes I made to the command(static methods instead of importing the simple-twitch-api library)

**Comment by Bacon-Fixation** [comment]
@galnir  it's a New Folder,New Clone, New Installs and it doesn't work on 
Windows 10
Ubuntu
Raspberry OS 10

if the User is online when you perform a `!tso` it will error saying the Message cannot be empty

**Comment by galnir** [comment]
I've narrowed it down to:
!tso Mochtroid - works
!tso quixarcade - doesn't work

**Comment by Bacon-Fixation** [comment]
Oh thank god i felt like i was going crazy <3

**Comment by galnir** [comment]
> Oh thank god i felt like i was going crazy <3

The problem is probably in the MessageEmbed in line 74. Something there causes node to throw an error. You can see this by adding a console.log call in line 89, it won't log it

**Comment by Bacon-Fixation** [comment]
yeah i had the same result

**Comment by Bacon-Fixation** [comment]
the data is there Before the offlineEmbed But not After it
image

**Comment by Bacon-Fixation** [comment]
@galnir the getGame method doesn't appear in the Statics at the bottom of the file

**Comment by Bacon-Fixation** [comment]
@galnir I fixed it !!!!!!!

**Comment by Bacon-Fixation** [comment]
i have move this build to my pi and works flawlessly

it was missing the whole `static getGames` section for the onlineEmbed
i just Added it to your revision of twitchStatus.js

**Review by galnir — APPROVED** [review]

**Pull request merged**
