### PR TITLE
Ka1-s - ChatGPT command

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
All Credit goes to Ka1-s PR #786 <3

the original pr included more than just the addition of the chatGPT command

only changed to the original idea were
Translated to English (from Portuguese)
Made the Command Optional (depending on if `OPEN_API` is filled in)
used Deferred replies (was getting a `The application did not respond`, right before the response)

Much Love
-Bacon

### CODE REVIEW

**Comment by Natemo6348** [comment]
@Bacon-Fixation I can't seem to get the gpt command to show up, I have the api key in .env already, so I don't know why it's not showing up

**Comment by Bacon-Fixation** [comment]
Howdy @Natemo6348, it seems something has changed, and I am looking into it now,
 `Command Chat Input Error: Request failed with status code 401`
will make a PR when it's resolved. My apologies for the inconvenience 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Oh alright, I actually got it to show up finally. I will await further news for a fix for that error though

**Comment by Bacon-Fixation** [comment]
there is something up with how they calculate Tokens Per Minute (40k tpm limit) and Request Per Minute(3 rpm limit), currently been locked out with 429 errors (too many requests) making a request minutes apart and with less than 10 tokens each and after 3 requests over 10 minutes has lock me out all day, completely halting progress, i have made changes to max tokens per requests but i can't test them :(

Much Love
-Bacon

**Pull request merged**
