### PR TITLE
Twitch Api function separation from twitchstatus.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
This is what #382's Files were supposed to look like (07a5b10) but would never save correctly when I commited from my main account 

adds instructions on how to get the twitch features set up(client id/ secret key)

-Below is just copied from OP
Reworked all Twitch Features to reference a `twitch-api.js` for the situation where a user wants one feature and not both. 
This thought kept me up at night after twitch announcer was merged

also Fixes the Box Art for Online Embed in `twitchstatus.js` where previously only 5 games that could get passed the 'jpg' filter in the `setThumbnail()`

image

the console message that twitch key is missing in `config.json` was changed to reference all twitch related features instead of just `twitchstatus`
```
INFO: Twitch Commands removed from the list.
Make sure you have "twitchClientID" and "twitchClientSecret" in your config.json to use Twitch Features
```

I apologize for so many changes so quickly
it lets me add to the 'twitch-api.js' file for future features if any other calls to Twitch are needed (without the need to make 'twitchstatus.js' more complicated)

- Notes on test situations: 
If you are set up for `commandState true` and `!disable twitchstatus`  then twitch announcer will give an error when used in that server.
If 'twitchstatus.js' was removed then Twitch Announcer can't be used gives an error in all servers.

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
I should have a lot less commits per PR now that I'm not fighting GitHub(just hope I fix my main account because this is kind of a janky workaround IMO)

the last 2 commits were from an actual mistake on my part(finally!) and didn't have to keep committing to get the changes to keep the changes

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I should have a lot less commits per PR now that I'm not fighting GitHub(just hope I fix my main account because this is kind of a janky workaround IMO)

the last 3 commits were from an actual mistake on my part(finally!) and didn't have to keep committing to get GitHub to keep the changes

Much Love
-Bacon

**Comment by galnir** [comment]
> I should have a lot less commits per PR now that I'm not fighting GitHub(just hope I fix my main account because this is kind of a janky workaround IMO)
> 
> the last 3 commits were from an actual mistake on my part(finally!) and didn't have to keep committing to get GitHub to keep the changes
> 
> Much Love
> -Bacon

Imo you shouldn't use GitHub to commit features, just use Git through your terminal and VScode as your editor

**Comment by Bacon-Fixation** [comment]
It didn't matter what method I was using to commit anything from this account was messed with when it got to the repo 
https://github.com/galnir/Master-Bot/pull/382#issuecomment-748753815

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
There is no `simple-twitch-api` Dependency in this PR

**Review by galnir — APPROVED** [review]
Better that way, thanks :)

**Pull request merged**
