### PR TITLE
Create join.js 

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
A simple join command to move the music that is playing to your current channel
mentioned in #284

- Tested on
Windows 10
Ubuntu
Raspberry OS 10
Heroku
Glitch.com
repl.it

Much-Love
-Bacon

### CODE REVIEW

**Comment by galnir** [comment]
IMO this command's name should be changed to 'join', and 'join' should be changed to smt else. Most users associate 'join' with summoning the bot to a vc

**Comment by Bacon-Fixation** [comment]
i'm down for anything <3 
have a suggestion for the Welcome message join rename?

**Comment by galnir** [comment]
> i agree :D
> i'm down for anything <3
> have a suggestion for the Welcome message join rename?

Maybe !show-welcome-message or !welcome-message-show imo

**Comment by Bacon-Fixation** [comment]
kk will post changes soon i want to find a better away to emit a newMember

**Comment by Bacon-Fixation** [comment]
i will wait to change this or recreate after name change for a cleaner merger

**Comment by Bacon-Fixation** [comment]
There ya go my friend <3

**Comment by galnir** [comment]
Btw why does it require the user to be an Admin in order to use the command?

**Comment by Bacon-Fixation** [comment]
Cuz during testing some trolls kept calling it

**Comment by galnir** [comment]
> Cuz during testing some trolls kept calling it during music trivia or to just make it annoying to other members in the discord server

Trolls can abuse any command basically, !play smt then !skip repeatedly. Best you can do here is add throttling

**Comment by Bacon-Fixation** [comment]
it can be removed, it was more out of Habit because of the issues we encountered on the Mochtroid Discord server (went ahead and admin locked the play commands per request) he uses it to provide music to his viewers while he streams so its not pick up in the Twitch stream (DMCA Chaos right now on Twitch)

**Comment by Bacon-Fixation** [comment]
Admin restriction removed

**Comment by Bacon-Fixation** [comment]
Admin restriction removed

Much Love
-Bacon

**Pull request merged**
