### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by kmkm133**
Adding dockerfile for easy setup.

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
its missing the libs for Canvas support 

https://github.com/Automattic/node-canvas#compiling

**Comment by kmkm133** [comment]
Added the libs missing according to the documentation node canvas has.

**Comment by Bacon-Fixation** [comment]
I mean no disrespect <3,

I had a chance to test this out and just curious why the `ubuntu:20.04` version instead of `debian:10`? 
And why not add `RUN npm install` at the end to reduce a step for the user setting it up?

The Ubuntu asks for my geographic location?
tempsnip

debian:10 ran through without this question
image

- Suggestion
change line 1 to `debian:10`  instead of `ubuntu:20.04` to eliminate the location question
change line 18 to `/Master-Bot` to get rid of warning `WORKDIR paths should be absolute`
add line 19 `RUN npm install`

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Is it possible for ffmpeg to be missing if the image was created without ffmpeg being installed on the host?
`ubuntu:20.04` is smaller (~70mb) but it asks for geographical location 
where `debian:10` (~114mb) uses the same library list needed for canvas & does not ask for location during image creation.

Just what I found playing around with it, <3 I love this idea

Much Love
-Bacon

**Comment by galnir** [comment]
> `ubuntu:20.04` is smaller (~70mb) but it asks for geographical location (tarball set up)
> where `debian:10` (~114mb) uses the same library list needed for canvas & does not ask for location during image creation.
> and maybe add `nano` along with vim to create the config.json(for users not familiar with vim)
> 
> Just what I found playing around with it, <3
> I love this idea so I modified a copy of this
> uses debian:10
> adds ffmpeg and nano to the apt-get install section
> copy my old config.json and json.sqlite to the image (i have a copy of both in the local folder)
> added `RUN npm install` after the git clone
> added `npm i -g pm2` and `CMD ["pm2-runtime", "--raw", "index.js"]` so it would auto start the bot when the container was made
> and output the log to the quick info for the docker desktop program
> 
> final size ended up ~1.42gb for the image
> 
> Much Love
> -Bacon

How much time does the build take?

**Comment by Bacon-Fixation** [comment]
[+] Building 84.6s (12/12) FINISHED

**Review by galnir — APPROVED** [review]
💯 now we need a wiki page explaining how to initialize the bot on Docker, then add a link under 'resources' in README

**Pull request merged**
