### PR TITLE
More speedrunning stuff

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
- Adds a Speedrun Category in the Help List
Moves Src to Speedrun Category
image

- Preview
Adds `!speedrunner-stats` command 
Example `!pbs jaychalke`
image

- Tested On
Windows 10
Ubuntu
Raspberry OS 10

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
Having Trouble keeping the  Field data aligned with each other if you notice in picture # 3 has 2 times on it

**Comment by Bacon-Fixation** [comment]
Switched to pagination embeds to align the data correctly looking into an 'Inception' style FeildsEmbed inside the Pagination Embeds in order to better show Split Segment Data

**Comment by Bacon-Fixation** [comment]
Bugs worked out and Finally Error Free

**Comment by Bacon-Fixation** [comment]
Should Be Ready to Go

Much Love
-Bacon

**Review by galnir — CHANGES_REQUESTED** [review]
I ran some tests and stumbled upon something. If you attempt to look up a user who doesn't exist or a user that has no scores it throws these errors in chat:
```
An error occurred while running the command: TypeError: message.say(...).delete is not a function
You shouldn't ever receive an error like this.
An error occurred while running the command: TypeError: Cannot read property 'cover_url' of null
You shouldn't ever receive an error like this.
```

**Review by galnir — APPROVED** [review]
solved it

**Comment by Bacon-Fixation** [comment]
Just curious what query term triggered this I would like to run it through `!src` to see if it has the same issue since the gathering method is similar

**Comment by galnir** [comment]
> Edit: Never mind I ran into it too with the unfixed version of the PR <3 Nice
> `!src` testing time
> 
> Just curious what query term triggered these errors, I would like to run it through `!src` to see if it has the same issue since the gathering method is similar
> 
> Is that eslint warning on Vim? (I'm just starting to play with Vim :D cuz why not)
> I haven't seen that one before on VS Code
> 
> Much Love
> -Bacon

query anything random like ajflkafklfjasfklkn214

**Pull request merged**
