### PR TITLE
Create avatar.js

### PR DESCRIPTION
**Pull request by Natemo6348**
As requested by @kizule #341 
May still need testing just in case
Working on repl.it

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
:D You beat me to it

**Comment by Natemo6348** [comment]
If you want to change anything, feel free to do so!

**Comment by Natemo6348** [comment]
@Bacon-Fixation after a bit more testing, I found that it doesn't work with .gif avatars, just sends a .jpg
Happen to know how to fix that?

**Comment by Bacon-Fixation** [comment]
user.displayAvatarURL({format: "png" | "jpg" | "gif" | "webp", size: 1024}) maybe

**Comment by Bacon-Fixation** [comment]
@Natemo6348  Try  `.setImage(user.displayAvatarURL({ dynamic: true }))` on line 26

**Comment by Princevikas** [comment]
hey buddy can you modify it for heroku hosting please ,it will be great help

**Comment by Natemo6348** [comment]
@Princevikas is it not working on Heroku?

**Comment by Princevikas** [comment]
> 
> 
> @Princevikas is it not working on Heroku?

bot going offline after 60 seconds

**Comment by Natemo6348** [comment]
When it goes offline, what does it say in the logs?

**Comment by Princevikas** [comment]
> 
> 
> When it goes offline, what does it say in the logs?

[bot logs.txt](https://github.com/galnir/Master-Bot/files/5637103/bot.logs.txt)

**Comment by Natemo6348** [comment]
check #337 where I explain how to fix that by changing the Dyno it runs on

**Comment by Princevikas** [comment]
> 
> 
> check #337 where I explain how to fix that by changing the Dyno it runs on

did that alr and it showing this
[nlogs.txt](https://github.com/galnir/Master-Bot/files/5637151/nlogs.txt)

**Comment by Natemo6348** [comment]
that doesn't really give me much to work with. could you try running it again and see if it gives you an error instead of it just saying it crashed?

**Comment by Bacon-Fixation** [comment]
@Princevikas  Check out my post on this error [Here](https://github.com/galnir/Master-Bot/issues/337#issuecomment-738116857)

**Comment by Princevikas** [comment]
> @Princevikas  Check out my post on this error [Here](https://github.com/galnir/Master-Bot/issues/337#issuecomment-738116857)
> 
> your log shows Web Scale is enabled, Remove it to have the bot run for more than 1 minute
> (Heroku Only Issue) Master-Bot doesn't have a Port defined for Heroku Web Scaling for Heroku's Dyno Engine

@Bacon-Fixation  still success brother

**Comment by Bacon-Fixation** [comment]
@Princevikas did you run after

**Comment by Bacon-Fixation** [comment]
@Princevikas `heroku ps:scale web=0`

**Comment by Bacon-Fixation** [comment]
@Princevikas i apologize I missed typed `heroku ps:scale web=0`  if that doesn't help 

I have a few more questions (you can post your response in the issues #337 <3)
Are you using a pipeline in Heroku?

Is this a clone or a Download of Master-Bot?

Did you make sure all the Depenency's are installed? (node 12+, python2.7, ffmpeg, etc)

Were there any Errors during the `npm i` command?

If so what were they?

Has the bot worked for you before or is this a new Bot for you?

I want to help you if I can and if I am unable this should give some additional info to help resolve your issue 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
@Bacon-Fixation I need your help. I was testing my avatar command, and I noticed that it usually makes the avatar blurry. Happen to know how to fix this? If not, know anyone that does?

**Comment by Bacon-Fixation** [comment]
im not sure on that one

**Comment by galnir** [comment]
It's actually working fine for me, pull the new package.json changes and enter ```npm i```, I changed discord.js to stable from master

**Comment by Natemo6348** [comment]
> im not sure on that one,
> do you know if the source was a low res image ?

@Bacon-Fixation that might be what it was


> It's actually working fine for me, pull the new package.json changes and enter `npm i`, I changed discord.js to stable from master

@galnir ok I will do that right now

**Review by galnir — APPROVED** [review]
Made a minor change, this is good to go

**Pull request merged**
