### PR TITLE
Update mute.js

### PR DESCRIPTION
**Pull request by Akikowo**
Make the code simpler

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
this will trigger it to mute people that have the same name

**Comment by Akikowo** [comment]
@Bacon-Fixation the Commando will ask you to specify the member's name don't worry about it.
On your case you can use !mute @Bacon Fixation

**Comment by Bacon-Fixation** [comment]
It missed its target

**Comment by Akikowo** [comment]
You need to mention them with Discord or use ID instead of mention them

The commando will think thats Bacon is member and Fixation is the reason so you can try ```!mute "Bacon Fixation"``` instead of ```!mute Bacon Fixation```

**Comment by Bacon-Fixation** [comment]
it can mute more than what the message shows without telling the user

**Comment by Akikowo** [comment]
I don't know what your issue is it's doesn't happen with me 🤔

**Comment by Akikowo** [comment]
Screenshot_20201125-144303_Discord
Full audit log

**Comment by Bacon-Fixation** [comment]
image
image
image

it still muted both

**Comment by Akikowo** [comment]
Did you remove the "Muted" role before execute the command?

**Comment by Bacon-Fixation** [comment]
of course
i used your unmute

**Comment by Akikowo** [comment]
I can't understand your issue the commando will return only one member that specific in the messsge

**Comment by Bacon-Fixation** [comment]
Yeah, I'm not sure why its happening either, I'm just reporting my results 

this showed up on
Raspberry OS 10
glitch.com
and 
repl.it

**Comment by Bacon-Fixation** [comment]
They are all fresh `npm installs`

**Comment by Bacon-Fixation** [comment]
I will look deeper into what's making it do this. I really want this to be included, I'm really impressed with the speed difference

**Comment by Bacon-Fixation** [comment]
I can't seem to stop this from happening on my Pi's

**Comment by Bacon-Fixation** [comment]
Ran into similar Random execution issues due to placement in PR#323 possibly related ?

**Comment by Natemo6348** [comment]
@Bacon-Fixation I'm surprised Bacon on GitHub hasn't come here asking why they keep getting mentioned lol

**Comment by galnir** [comment]
You guys probably have different versions of discord.js and discord.js-commando

**Review by galnir — APPROVED** [review]

**Comment by Bacon-Fixation** [comment]
No worries I can revert for my PI, it mutes more than the intended target  with current discord js commando

**Pull request merged**
