### PR TITLE
Added a Twitchstatus command

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Adds a twitch status command `!twitchstatus streamer-name` using simple-twitch-api
https://www.npmjs.com/package/simple-twitch-api
auto-disables if twitchCleintID or twitchToken are missing/deleted from your config.json when you launch the Bot!

- Command Usage
`!twitchstatus mochtroid`  `!tso mochtroid` or `!tso https://twitch.tv/mochtroid`
- Online
image

- Offline
image

### Setup Instructions
- **Dependency**
`npm i simple-twitch-api`

- **Twitch**
A Twitch account is needed, if you don't already have one you can [Click Here](https://www.twitch.tv/signup)
Login to Twitch's Dev Portal Dashboard with your Twitch login Info
https://dev.twitch.tv/console/apps

- **Creating a Twitch Application** 
Click on 'Register Your Application' in Dev Portal Dashboard.
Go ahead and 'Name' your App.
For 'OAuth Redirect' enter `http://localhost`
Select a 'Category', I used 'Application Integration'
........make sure you're not a robot then click 'Create'

- **Getting your Twitch Application Info**
Now that you have an app created click 'Manage' on your new creation
You should now see your Client ID
Click 'New Secret' to see your Secret Token
Now we can add them to your `config.json` file

Example of what `config.json` should look like when you're done
```
{
  "prefix": "!",
  "discord_owner_id": "Your-Discord-ID",
  "token": "Your-Bot-Token",
  "tenorAPI": "tenor-API-key",
  "newsAPI": "news-api-key",
  "youtubeAPI": "youtube-api-key",
  "yandexAPI": "yandex-api-key",
  "geniusLyricsAPI": "genius-api-key",
  "twitchCleintID": "Your-Client-ID",
  "twitchToken": "Secret-Token"
}
```
- [**Twitch's API Rate Limit**](https://dev.twitch.tv/docs/api/guide#rate-limits) when using `!twitchstatus` command
The Twitch API Rate Limit is 800 total calls per minute
1. Online message:  3 calls  ~266 per minute
2. Offline message: 2 calls ~400 per minute
3. Not found message: 2 calls ~400 per minute
4. Invalid message:  2 calls ~400 per minute
5. Error message: 1 call ~800 per minute

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
This should be ready for merge now






Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
This should be ready for merge now

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I tried to be more thorough with handling errors and people that are new or updating Master-Bot
 
- **_Tested On_**
Windows 10
Raspberry OS 10(Debian)

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
This one should be a Complete Package Too

took much longer to test 100 streamers for errors

- Passed on
Windows 10
Ubuntu
Raspberry OS 10

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
You can include repl.it and Glitch.com to the Passed Platforms
went ahead and tried them to for this command(trying to make absolutely sure that it works everywhere)

**Comment by Bacon-Fixation** [comment]
Converted to Draft Found a Bug with some jpg's are missing its header and won't embed properly for the Thumbnail

**Comment by Bacon-Fixation** [comment]
if the thumbnail is a .jpg it will use the Streamers Profile picture instead so it doesn't show a buffering symbol when it encounters a jpg (come to find out most of the jpgs on twitch are headerless and don't play nice with Message embeds)

**Review by galnir — APPROVED** [review]
I generally avoid importing libraries and using only 4 methods. I removed the need for the simple-twitch-api by implementing those myself

**Comment by Bacon-Fixation** [comment]
`!twitchstatus Mochtroid` Command gives me an error after dependency removal (All systems)
Deleted node_modules folder and ran `npm i` 
i have matched the name change (twitchClientSecret) in my `config.json`  

[ 'Bacons Room Of Doom!!', 'Mochtroid', "Bacon's Bot Testing Grounds" ] Connected!
(node:13420) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (C:\Demo\Master-Bot\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Demo\Master-Bot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation It worked at least for the use cases I tried, I'll look into it

**Comment by Bacon-Fixation** [comment]
I've posted a version that uses the simple-twitch-api just for peeps that may encounter the same error

**Pull request merged**
