### PR TITLE
Create nickname.js

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Originally Posted #335 by Zeroo000

but this fixes the 'permissions' error message when doing `!nickname @ taguser newNickname` or `!nickname userID newNickname`

- `!nickname`  Preview
image
image
image
image

- Error Messages (if one occurred)
image
image
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
The returns were removed because during testing  situations `?nickname @ <id number> newName` (a space between @ and number)  
image
this was odd to get this message instead of the error message that is on line 21 for the Member arg

**Comment by Bacon-Fixation** [comment]
I was bored and Zerroo000 never replied

**Comment by galnir** [comment]
I can't get it to work, tried tagging the member, passing the member's name and the member's ID

**Comment by Bacon-Fixation** [comment]
set to draft till i figure out why your results differ like that. `!nickname members-name` should not work without the @

**Comment by Bacon-Fixation** [comment]
@galnir i think you tried to change a member that has the same role or higher with will give you an error

**Comment by Bacon-Fixation** [comment]
added another message when a lower role tries to change  a higher one

**Comment by Bacon-Fixation** [comment]
added another message when a lower role tries to change  a higher one

**Comment by Bacon-Fixation** [comment]
added another message when a lower role tries to change  a higher one
changed embides to use displayname instead of ID

image

side note this should be the last time i need to use Bacon-Sensation - ended up being the VSCode github extension i removed all Github options from VSCode to stop it from jumbling my commits (even if vscode wasn't the method of commit i.e GIT Bash or GitHub Desktop)

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Added another message when a lower role tries to change  a higher one
changed embeds to use `user.username` instead of `id` - the id number meant nothing to most command users(i asked 20 people in a discord server to try it out, and they gave me some feedback, a little over half were like "what's with the numbers ?" :D)

image

and i tried with tags
image

side-note this should be the last time i need to use Bacon-Sensation - ended up being the VSCode github extension i removed all Github options from VSCode to stop it from jumbling my commits (even if vscode wasn't the method of commit i.e GIT gui, Git CLI or GitHub Desktop)

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Triple checked 
image

**Comment by Bacon-Fixation** [comment]
I think I found the situation that you ran into @galnir but this also effects Mute, and Unmute not just Nickname
if the member that is requested has not sent a message after the bot is launched that requested member is not found at all by their Tag
image

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I apologize if I sound like a punk :D <3 (I've read what I wrote like a million times) I never want to over step or sound pushy and never want to upset/offend or feel like I'm talking down to anyone, I'm not the strongest speaker when talking to people 


I really love this bot, it gets me through work and something to work on during the winter and really appreciative that it was made <3 and probably a little eager to help :P

As Always Much Love
-Bacon

**Review by galnir — APPROVED** [review]
Well done, I tested it and it works great now

**Pull request merged**
