### PR TITLE
Created rock, paper, scissors

### PR DESCRIPTION
**Pull request by ModoSN**

### CODE REVIEW

**Comment by Natemo6348** [comment]
@ModoSN could you add a choice that you make before the bot chooses or is there not meant to be a choice

**Comment by ModoSN** [comment]
@Natemo6348 It replies so it is kind of for two people rather than playing against the bot

> Modo does /rps
> Bot says "@Modo ROCK!"
> Friends does /rps
> Bot says "@friend PAPER!"

**Comment by Natemo6348** [comment]
ok, well I made changes to it and added it to my bot to play against the bot

**Comment by galnir** [comment]
Closing this pull request since this feature was merged in #224 :)

**Pull request closed without merging**
