### PR TITLE
2 Player Game of Tic-Tac-Toe

### PR DESCRIPTION
**Pull request by Bacon-Fixation**
Addressing request #552 

- Example with an attempt to add shadows :D
image

Much Love
-Bacon

### CODE REVIEW

**Comment by Bacon-Fixation** [comment]
Minor Tweak
shows your selection Row/Column for better clarity
image

**Comment by Bacon-Fixation** [comment]
Adds a Game over state when no more moves are available 
image

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Last change ready for review (no rush)

Now uses Discord Avatar if one is available (already working on the same thing for connect4)
image

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Ooh I love it

**Review by galnir — APPROVED** [review]
Well done

**Pull request merged**
