### PR TITLE
Added new fun comamnds

### PR DESCRIPTION
**Pull request by TheJYT**
Working on some new fun cammnds to add to the bot. Took me a while to figure out how API Wrappers work but hers 2 commands i've been working on using the neks.life API library.

!waifu - Replys with an image of your waifu
!dog - Replys with an image of a cute doggo

### CODE REVIEW

**Comment by galnir** [comment]
I like these commands but I'm against the idea of adding a package(nekos.life) for the sole purpose of getting images. Do you think you can rewrite these commands to use the tenor gif API?

**Comment by TheJYT** [comment]
> 
> 
> I like these commands but I'm against the idea of adding a package(nekos.life) for the sole purpose of getting images. Do you think you can rewrite these commands to use the tenor gif API?

Sure! On it immediatly.

**Comment by Natemo6348** [comment]
@TheJYT if you want, I have a dog command that I made by changing the cat command slightly and you could use that and change whatever you want

**Comment by galnir** [comment]
> @TheJYT if you want, I have a dog command that I made by changing the cat command slightly and you could use that and change whatever you want

You're welcome to open a pull request ;)

**Pull request closed without merging**
