### PR TITLE
Dashboard (work in progress)

### PR DESCRIPTION
**Pull request by galnir**
Starting to work on a dashboard for guild owners to manage and change settings. The dashboard is separated from the 'bot' files so there is no obligation to setup the dashboard project in order to run the bot.

The dashboard is a React project that uses Remix which I found very nice to work with. Styling is done with tailwind (I prefer styled-components but it doesn't integrate well with Remix at this point). It communicates with the DB through a REST api that is exposed using the plugin-api that Sapphire offers, the routes are under src/routes in the bot/ folder.

@Bacon-Fixation All the new features you're planning to add should be on this branch because the plan is to have the option to enable/disable features via the dashboard.

Current state of the dashboard:
- Login via discord oauth (requires a secret you can generate in the developer portal), choosing which server to manage (only servers the bot is in) and the ability to edit the welcome message and also to enable / disable it.
- enable / disable commands
- enable/ disable temporary channels feature

### CODE REVIEW

**Comment by galnir** [comment]
@Bacon-Fixation Ofc any critical bug fixes you write (like fixing issues related to the music feature) should be on a separate PR that I'll merge into the main branch asap

**Comment by galnir** [comment]
@Bacon-Fixation If you have any ideas for features you think should be on the dashboard please lemme know :)

**Comment by galnir** [comment]
@Bacon-Fixation Can you undo the constantly updating progress bar changes? It's very buggy and unpredictable. I'll look into a solution in the future tho

**Comment by galnir** [comment]
@Bacon-Fixation Did you get a chance to try the dashboard? If yes, did you experience any bugs?

**Comment by Bacon-Fixation** [comment]
@galnir a feature this neat, I absolutely have played around with it quite a bit :D, tailwind is neat, only 2 things I can report is when you are at the guild selection that guild icon images don't seem to load and looking at `guild.icon` it only seems to have the hash for the url 


`dashboard/app/routes/dashboard/index.tsx` line 53 (seems to work)
```
              img={
                `https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}` ??
                "generic-image.png"
              }

```

and i get a Warning that 'purge' is deprecated and to use 'content' instead in `dashboard/tailwind.config.js` line 4

Much Love
-Bacon

**Comment by galnir** [comment]
> @galnir a feature this neat, I absolutely have played around with it quite a bit :D, tailwind is neat, only 2 things I can report is when you are at the guild selection that guild icon images don't seem to load and looking at `guild.icon` it only seems to have the hash for the url
> 
> `dashboard/app/routes/dashboard/index.tsx` line 53 (seems to work) edit (corrected ternary, check `guild.icon` :D)
> 
> ```
>               img={
>                     guild.icon ?
>                        `https://cdn.discordapp.com/icons/${guild.id}/${guild.icon}` :
>                        "generic-image.png"
>               }
> ```
> 
> and i get a Warning `` The `purge`/`content` options have changed in Tailwind CSS v3.0. `` line 4
> 
> Much Love -Bacon

Fixed, thanks for pointing it out. I also finished the UI for the temporary channels feature you can check it out (make sure bot/ and dashboard/ are up to date and I think you need to `npx prisma migrate dev` as well).
Enabling it should create a category with a hub channel inside it, when you enter it you should get redirected to your own VC with permissions). Disabling it should delete the category and the hub.

**Comment by Bacon-Fixation** [comment]
some ideas,
maybe stats for bot owner like qps*,  uptime(bot/redis/postress), Players Active*, bandwidth usage, # of songs played
add a DB entry when inviting the bot from the Dashboard, and redirect back to the Guilds Dashboard page after inviting the bot to a guild.

is the temp voice channel going to have a `/` command for it as well ?


Much Love
-Bacon

**Comment by galnir** [comment]
> some ideas, maybe stats for bot owner like qps*, uptime(bot/redis/postress), Players Active*, bandwidth usage, # of songs played add a DB entry when inviting the bot from the Dashboard, and redirect back to the Guilds Dashboard page after inviting the bot to a guild.
> 
> is the temp voice channel going to have a `/` command for it as well ?
> 
> Much Love -Bacon

I might add slash commands to control the temp channels

**Comment by galnir** [comment]
@Bacon-Fixation I'm going to merge this since I think the dashboard's stable enough to be on main. I will continue to add more features I have in mind.
About the reminder feature, I've looked into it and it looks good but I'm not entirely sure it's considered best practice to store them in the DB. I think storing them on Redis is better and you can do so by giving them TTL(time to live) and when it expires you catch the event and send the reminder. Since I'm not entirely sure I will look into it more deeply soon

**Comment by Bacon-Fixation** [comment]
Sounds good, may be a few days before I get back in town to work on it some more, i will move it to a draft while i convert it to redis. 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@galnir i apologize about delays, i am still out of town, and didn't expect it to be extended,
I can close the reminder pr and remake it in the near future for the main branch, 
I don't exactly have an eta as of yet (i'm here until job is complete), figured would mention that there as a situation change.

When it rains, it pours.... 

Much Love
-Bacon

**Pull request merged**
